### ISSUE TITLE
Feature request? Threading :)

### ISSUE THREAD

**Issue by Viss** [ChrisTruncer/EyeWitness#101]
When scanning 'the whole internet' or 'an entire country', one gets many many results. In the 100's of thousands. Would you consider adding threads so that the user could specify at the commandline something like --threads=500 ?

**Comment by rvazarkar** [comment]
I have become coder, completer of requests!

The nuke_it_all branch now has fully functional multiprocessing, with threading. You can choose your number of threads using --threads. Going to leave this open until we merge it all into master.

nuke_it_all is a complete rewrite with a whole bunch of quality of life improvements and efficiency updates. So check it out!

**Comment by ChrisTruncer** [comment]
This has now been merged into master! :)
