### ISSUE TITLE
Creating files in wrong directory

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#112]
If you run the app from a directory other than the one it is installed in it creates the results directory in the install directory but then assumes it is in the current directory when creating the files.

```
~/tools/recon/EyeWitness/EyeWitness.py -f nmap/web.xml 

#############################################################################
#                               EyeWitness                                  #
#############################################################################

Traceback (most recent call last):
  File "/home/robin/tools/recon/EyeWitness/EyeWitness.py", line 1154, in <module>
    operating_system)
  File "/home/robin/tools/recon/EyeWitness/EyeWitness.py", line 369, in folder_out
    with open(join(output_folder_name, "style.css"), 'w') as css_file:
IOError: [Errno 2] No such file or directory: '02092015_122117/style.css'

**Comment by ChrisTruncer** [comment]
Nice, that’s a good catch.

I’ll get that fixed.

Thanks!

-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On February 9, 2015 at 7:24:31 AM, Robin Wood (notifications@github.com) wrote:

If you run the app from a directory other than the one it is installed in it creates the results directory in the install directory but then assumes it is in the current directory when creating the files.

~/tools/recon/EyeWitness/EyeWitness.py -f nmap/web.xml  

#############################################################################
#                               EyeWitness                                  #
#############################################################################

Traceback (most recent call last):
  File "/home/robin/tools/recon/EyeWitness/EyeWitness.py", line 1154, in <module>
    operating_system)
  File "/home/robin/tools/recon/EyeWitness/EyeWitness.py", line 369, in folder_out
    with open(join(output_folder_name, "style.css"), 'w') as css_file:
IOError: [Errno 2] No such file or directory: '02092015_122117/style.css'

**Comment by ChrisTruncer** [comment]
I believe this should be fixed now.  Thanks for letting me know about it.
