### ISSUE TITLE
ts3100 default creds

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#114]
Doubt this is enough for a good signature but it is from a TS3100 Tape Library. Default creds:

admin/secure
```
<HTML>
<HEAD>
<TITLE></TITLE>
</HEAD>
<BODY>
<SCRIPT LANGUAGE="javascript">
<!--
	location='login.ssi'
-->
</SCRIPT>
</BODY>
</HTML>

**Comment by digininja** [comment]
Unfortunately this also matches an MSL2024 which has the password 00000000 for admin. Admin is picked from a drop down, not entered in a text box.

**Comment by ChrisTruncer** [comment]
I think this might be a little too generic for the source code.  The only main line that would differentiate it is the login.ssi line.  I could really go either way on this one, thoughts?

**Comment by digininja** [comment]
Would be a bit of a rewrite but how about returning multiple options rather
than just one. You then say either "it is xxx" or "signatures match the
following xxx yyy".

This would let you handle genetic snippets like this one and the other I
sent over.

**Comment by ChrisTruncer** [comment]
This is a good idea i need to get added in (identifying potential multiple sigs).  It would require a little bit of re-write, but nothing too major (I don't think).  I'll try to get this added in after my initial release of the next version.

**Comment by ChrisTruncer** [comment]
I just looked into this, and now have it setup to display any signature that it hits vs. just the first one.

This MAY lead to some incorrect signatures being displayed, but hopefully a minimal amount if any.

I think I can finally close this one out now :)
