### ISSUE TITLE
Imagerunner iR-ADV C5235 creds

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#115]
Imagerunner iR-ADV C5235 

Admin login
7654321/7654321

Source
```
<HTML><HEAD><META http-equiv=Refresh content="0; URL=http://1.2.3.4:8000/rps/"></HEAD></HTML>
```
Headers
```
Page Title: Unknown
Transfer-Encoding: chunked
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: CANON HTTP Server
Pragma: no-cache
Cache-Control: no-cache,no-store,max-age=0
Date: Mon, 09 Feb 2015 12:32:34 GMT
Content-Type: text/html;charset=iso-8859-1

**Comment by digininja** [comment]
Also matches iR-ADV C5250 which has default PIN 1234

**Comment by digininja** [comment]
And an iR-ADV 4251, probably covers the whole of their range of products.

**Comment by ChrisTruncer** [comment]
Is that the only source code for the web page that Eyewitness pulls when scanning it?  Unfortunately, I can't make a signature (at least not currently) based off of the server headers, and the html code might just be too minimal, although, it is a little unique.  I could go either way on this signature too, think source code is unique enough for it?

**Comment by digininja** [comment]
See comment in ticket #114.

Any reason you don't check headers as well a body?

**Comment by ChrisTruncer** [comment]
OK, I'll check there.

Headers, that can be impacted by the server itself, along with the application, correct?  For looking at creds of web apps, I just didn't want it to miss anything just because the headers might be different based on the server running, or configuration of the server.

**Comment by digininja** [comment]
Some headers will be but others won't. Things like printers though will
have some fairly fixed ones such as the server header. On phone now so
can't check but one of these I submitted has a very obvious server value
from what I remember.

**Comment by ChrisTruncer** [comment]
I think for the time being, I can't do headers, at least how I have the app currently designed.  When looking for signatures, it's an all or nothing comparison.  Source code, that's not a problem (typically), however I can't guarantee that all the headers would be there each time from the server.  Certain situations it might work, but I don't know if it could universally (at least how I am trying to figure out how to engineer it).

**Comment by digininja** [comment]
Having all or nothing on the source could definitely be a problem, what
about the apps that do a redirect but give content in the HTML body of the
redirect that could be fingerprinted. The body will likely have the IP or
server name for the redirection so an all or nothing match will fail.

If you want to get fancy then you should allow regular expressions in the
matches. I don't think that would be that hard to add, the hardest part
would be escaping all the stuff that shouldn't be in the regex but I think
there is a function for that.

**Comment by ChrisTruncer** [comment]
I don't believe we can get this added in currently.  We'll have to debate if we can do headers in the future.
