### ISSUE TITLE
Schmoo Branch -- Stuck on Page

### ISSUE THREAD

**Issue by korang** [ChrisTruncer/EyeWitness#121]
While running thru a scan list I hit a page that ran into issues.  http://199.38.150.73:80 .  The error on the page states:  Javascript is not enabled.  It must be turned on in order for the application to run.  The page then never finishes loading causing the script to get "stuck" on the page.  I had to hit the x to stop loading page to get the script to continue.

**Comment by ChrisTruncer** [comment]
That looks to be a one off page.  I loaded it in a regular browser (not one being driven by EyeWitness), and it continues to reload that page.  It doesn't look like it is a browser popup (at least to me), but it is the page just being reloaded/refreshed like every second.

On the other hand, I also did add in code to check and see if a popup is displayed, and if so, close it out.  So ideally if a popup does appear for you, it should close it.  Let me know if you still have any issues with it.
