### ISSUE TITLE
Enhancement: support for massscan

### ISSUE THREAD

**Issue by ebrinkster** [ChrisTruncer/EyeWitness#124]
I had the idea that it'd be neat to integrate compatibility for masscan in eyewitness.  Thoughts? -- Link: https://github.com/robertdavidgraham/masscan

There are various formats for output, one of which is XML.

**Comment by ChrisTruncer** [comment]
This is already in there :)

**Comment by ebrinkster** [comment]
Ahh gotcha, I was thinking to myself shortly after I made this that massscan has the XML option that I believe was adopted from nmap outputs.

Pardon the mistake.

**Comment by ChrisTruncer** [comment]
Ha, no worries on the mistake, not a problem at all.  It was only added in maybe a month ago, so it was very recent.  Thanks for the suggestion though, and let me know if you have any others!
