### ISSUE TITLE
Segmentation Fault Constant

### ISSUE THREAD

**Issue by ebrinkster** [ChrisTruncer/EyeWitness#125]
I'm noticing lots of segmentation fault's when scanning large ranges that contain 500+ or more targets.  Is it possible to provide the capability to start off a scan when the segmentation fault occurs on a previously started (but stopped abruptly) scan?

**Comment by ebrinkster** [comment]
My short term solution has to utilize a bash script with a loop so if EyeWitness crashes it'll just continue on to the next IP though.

**Comment by ChrisTruncer** [comment]
Ugh, that's kind of annoying that you have to do that.  By chance, have you tried using the updated beta branch?

I'm thinking the issue is likely with Ghost.  When running it, it does hit a bunch of segfaults.  The updated beta branch has selenium, and imo is much more stable, I'll be interested to hear if you've tried it.

**Comment by ebrinkster** [comment]
I'll give the updated beta version a try.  I'm sure it's an issue with Ghost.

**Comment by ChrisTruncer** [comment]
Yeah, I apologize for it, it's definitely a shared frustration.

**Comment by digininja** [comment]
Just so you know that it isn't you, I've just had a seg fault on the latest version as well, will try the beta.

**Comment by ChrisTruncer** [comment]
Ok, definitely let me know with the beta and using selenium (with the --web option).  I keep checking the ghost repo, and it looks like their last commit was a while ago, so I'm a little concerned that dev has stopped on it in a semi-functional state, but still has obviously errors.

If that's the case, I'll probably end up removing ghost to stop that issue, and as much as I tried to stay away from it, I might add in phantomjs so people have a second option.

**Comment by digininja** [comment]
This was on a fresh Ubuntu install and died at 73/95 sites.

**Comment by ChrisTruncer** [comment]
Did selenium crash?  Could you pastebin the output if it happens again?

**Comment by rvazarkar** [comment]
The new rewrite should fix a lot of these issues. Ghost is dead, long live phantomjs

**Comment by ChrisTruncer** [comment]
This should be set now!
