### ISSUE TITLE
Kali section of setup missing netaddr

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#126]
The Kali section of setup.sh is missing the python-netaddr package.

Just set it up on the Raspberry Pi Kali install and works fine except this package is not installed by default.

**Comment by ChrisTruncer** [comment]
Added that in.  I thought it was already built into Kali, so thanks for reporting this.

**Comment by digininja** [comment]
May be in main distro but not in Raspberry Pi edition.
