### ISSUE TITLE
fail gracefully if no Ghost

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#128]
If Ghost isn't installed you get the following error when running the app

    $ ./EyeWitness.py
    Traceback (most recent call last):
      File "./EyeWitness.py", line 14, in <module>
        import ghost as screener
    ImportError: No module named ghost

It should ideally fail gracefully and explain how to run the setup script.

**Comment by digininja** [comment]
same for missing fuzzy wuzzy on beta branch

**Comment by rvazarkar** [comment]
I've added import checks to everything on nuke_it_all (I think), prompting you to run the setup script.
