### ISSUE TITLE
add a version argument

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#129]
It would be good to have a -v argument to show the current version number, there is no easy way to tell if I'm running the beta or the main version at the moment without asking Git

**Comment by ChrisTruncer** [comment]
I don't think we're going to add this in.  Unfortunately, this is kind of confusing currently.  But we plan on merging to master within a month I believe.  When we do, there will not be any other versions where anyone will have to worry about being on the wrong branch, so ideally this won't be an issue then.

**Comment by digininja** [comment]
There are ways with subversion and CVS to automatically add a version
number when code is checked in so that when it is checked out you always
know what version you are running. I've just had a quick search and didn't
see an obvious way to do this with git and Github but it may be possible.

I think it would still be worth adding a version, if only to help you
support people who are running it from a distro like Kali where there is a
good chance they aren't on the latest version.

**Comment by ChrisTruncer** [comment]
I think we should be good with this issue, since we're always going to tell people to use master.  The extra branches were just for our rebuilding purposes.  In the future, master will be the one to use, and only patches are a new branch.
