### ISSUE TITLE
python-dev package missing

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#130]
Debian requires the python-dev package installed so the new beta setup.sh script will work so needs adding tot he package list.

**Comment by digininja** [comment]
I also get this

    /usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

so suggest adding the python-levenshtein to the package list.

**Comment by digininja** [comment]
And selenium requires Firefox so in Debian I had to install iceweasel but still doesn't work.

**Comment by ChrisTruncer** [comment]
This is in there now
