### ISSUE TITLE
 Error: Please provide a valid folder name/Path

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#133]
Not sure what is causing this on the new beta but full.xml exists and is readable

```
$ /opt/EyeWitness/EyeWitness.py  -f full.xml  --web

################################################################################
#                                  EyeWitness                                  #
################################################################################

[*] Error: Please provide a valid folder name/Path

**Comment by ChrisTruncer** [comment]
Is it in the current directory of EyeWitness, and it's not seeing it?  Does the full path work?

**Comment by digininja** [comment]
Got it, it tries to create the output directory in the /opt/EyeWitness directory not in the current directory, as that directory is owned by root it wasn't writable by me and so that is what the error means.

I would expect the output to be done in the current directory and not in the location of the script.

You could also change the error message by checking if the folder exists but isn't writable and giving that as an explicit error message.

**Comment by digininja** [comment]
In case it wasn't obvious, I was in a different directory that was fully writeable by my user

**Comment by rvazarkar** [comment]
The nuke_it_all branch now uses your current working directory when provided with a relative or no folder as the directory output, along with a whole slew of updates and enhancements. Feel free to check it out and see if you can find anymore bugs!

Leaving this issue open until a full merge to master.

**Comment by ChrisTruncer** [comment]
We're merged now, so this should be set.
