### ISSUE TITLE
QT: QNetworkReplyImplPrivate error

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#134]
Got this while running the latest version against a basic site, browser hits it OK.

```
2015-05-12T22:11:39.1431465099 QT: QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

**Comment by ChrisTruncer** [comment]
Can you use the nuke_it_all branch?  Ideally, this shouldn't be in there anymore since we aren't using Ghost.

**Comment by ChrisTruncer** [comment]
I will leave this open until we actually merge it into master though, just to make sure we keep tracking it.

**Comment by ChrisTruncer** [comment]
This shouldn't be an issue anymore.  Thanks for letting us know
