### ISSUE TITLE
Rebuild from crash

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#135]
I've got a scan that was running and it died because of a seg fault. I've got 10's of screenshots and associated text files, is there an easy way to build the report html page to go with what I've got so far?

**Comment by ChrisTruncer** [comment]
Which district are you using?  Our nuke_it_all branch doesn't use ghost anymore, which is the cause for all of the crashes (looks like it isn't supported anymore).

I need to build a VM of Debian to test and make sure the setup works on it. Also it does use selenium and phantomjs, so I want to see how they work on it as well.

We don't currently have a way to build a report off of a crashed instance unfortunately. I'm really sorry about the issues with ghost (assuming that's the problem).  I actually have some time I can dedicate to testing this on Debian, so I'll get downloading it now and do anything I can to help get you running.

**Comment by digininja** [comment]
Its an old scan from the original branch and it was Ghost that died.

I'll write a quick and dirty script to generate something that looks like
the official report from what I've got, shouldn't be to hard I don't think,
just a case of matching file names from source and screens and building
HTML.

**Comment by digininja** [comment]
Looking at what I've got there are a lot of cases where I've got a screenshot but no source file to go with it. The screenshots I've checked are normal ones of sites, not errors or fails.

Any ideas why this could happen?

**Comment by digininja** [comment]
Here you go, this is a quick hack to sort through all the screenshots and produce a report from them

https://gist.github.com/digininja/fad2e5cc8da19ff3bc60

**Comment by ChrisTruncer** [comment]
Wow, that's really awesome.  Do you mind if I include that in the current master branch (since it still has ghost in it)?  That would be great to use (full credit will be given to you).

Also, I just tested out the nuke_it_all branch in debian stable.  Setup script ran and just tested against a few websites, and it all works.  nuke_it_all is basically the final beta, where we made a ton of improvements from the original.  The biggest ones, is threading has been added in, and we've stopped using Ghost, so stability should be significantly better.

**Comment by digininja** [comment]
Feel free to use it however you want. There is no error checking or
anything nice like that so either warn people or add a bit, maybe prevent
overwriting of an existing report file.

It would also be good to know why there are missing source files, again,
either warn that it might happen or document why so people aren't wondering
about the message I put out.

For the new branch, I'm on site in about 2 weeks so will make sure its
installed and ready to test then.

**Comment by rvazarkar** [comment]
This should no longer be an issue. Resume support has been added into nuke_it_all. You can cancel a scan at any time and resume it again. If you run into a crash it'll let you resume the crashed instance as well.

**Comment by digininja** [comment]
Nice, thanks

**Comment by ChrisTruncer** [comment]
Thanks again for your script.  We do have one we wrote now that uses the sqlite database that is created when starting a scan.  But I did link to yours also in the blog post in case users want to use that too.
