### ISSUE TITLE
show critical first

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#137]
In the nuke_all branch, show critical pages first rather than hiding them away after the boring uncategorised stuff.

**Comment by rvazarkar** [comment]
I assume you're referring to the high value targets? If so, I can move
those up to the front, seems like a good idea

**Comment by digininja** [comment]
That's the one, move them up. Too much time in Nessus yesterday.

**Comment by rvazarkar** [comment]
Done

**Comment by ChrisTruncer** [comment]
The high value ones are now first.  Good call on this.
