### ISSUE TITLE
show number of requests

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#139]
I think in the master branch you print that you will process X records before doing the run, in nuke_all branch you don't. I'm importing from an nmap XML file if that matters.

I see the occasional "processed X of Y" as going through so assume you have the info before the script starts.

**Comment by rvazarkar** [comment]
I'll set it up so each segment outputs the number of hosts being captured.

**Comment by digininja** [comment]
Can you give an overall count at the start as well? The master branch does.

**Comment by rvazarkar** [comment]
When I say segment I mean http/rdp/vnc. So you'll get to total number of
hosts for the current protocol.

It's hard to just do a total when doing stuff like user agent switching
because there's no way to accurately calculate how many UA screenshot will
be taken

**Comment by digininja** [comment]
Thats what I wanted.

**Comment by rvazarkar** [comment]
Pushed this to nuke_it_all

**Comment by ChrisTruncer** [comment]
This should be in master now
