### ISSUE TITLE
404 detection failing

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#140]
don't know why but you've categorised a bunch of printers as 404 when there is a page there, you have source and a screenshot.  Manual check shows a 200 response code.

I'm going to add another ticket to help debug this

Oddly you show the content length as 0 but as I said, there is source.

**Comment by rvazarkar** [comment]
So there's some screwy stuff going on with error code detection mostly
related to urllib2 and ssl versions. I'm trying to figure out a better way
to detect stuff right now.

Sadly selenium doesn't expose the response code of the site so it requires
some strange workarounds

**Comment by rvazarkar** [comment]
Were you using --headless for this? Or --web

**Comment by digininja** [comment]
--web

**Comment by rvazarkar** [comment]
Interesting. Hopefully it shouldn't happen again, but let me know if you run into the same issue and if you can provide me a url to test with. urllib's behavior can be really strange, but thats how I'm deriving my response code

**Comment by rvazarkar** [comment]
I fixed a possible cause of this. urllib did not have a user-agent set, so it was possible for the responses to be different based on that. The request to get headers/response code will now use the same user-agent as your current driver

**Comment by ChrisTruncer** [comment]
I think this should be good now.  Please let us know if you still encounter this.
