### ISSUE TITLE
remove apt-get dist-upgrade

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#145]
I know I suggested it but having run the setup script I think you should drop the dist-upgrade.

As you are then explicitly doing installs on all the packages you need they will bring anything that is needed up to date. I think this is better than suggesting the user upgrades their whole system.

**Comment by ChrisTruncer** [comment]
Removed!

**Comment by digininja** [comment]
You now just need to make sure that you apt-get install all your
dependencies so whenever the setup.sh script is ran they will be updated.

**Comment by ChrisTruncer** [comment]
Yup, we're doing an apt-get update, and then an apt-get install for all the dependencies that we're installing from apt.

**Comment by digininja** [comment]
Sounds good.
