### ISSUE TITLE
HTTP on none standard

### ISSUE THREAD

**Issue by darryllane** [ChrisTruncer/EyeWitness#147]
I recently started writing something like this and came across Eyewitness, it looks great so far. I cant seem to find a way to specify which ports to check for http type services. Is there a way to specify ports? or does this just check port 80?

**Comment by rvazarkar** [comment]
You can just append the port in standard format. Url:port

**Comment by ChrisTruncer** [comment]
You can give EyeWitness nmap and nessus xml output.  EyeWitness will parse the XML file and then screenshot any webserver that was detected, on any port.

If giving EyeWitness a single text file with URLs on new lines, you can do

www.google.com
www.cnn.com:8080
etc..

**Comment by darryllane** [comment]
arr Awesome just what I was after Chris great. Thanks will have a play with it now.
