### ISSUE TITLE
User Reported Scanning Issues

### ISSUE THREAD

**Issue by ChrisTruncer** [ChrisTruncer/EyeWitness#148]
Pastebin links here:

http://pastebin.com/vUBWJrwM
http://pastebin.com/xu5J3N2R

**Comment by Viss** [comment]
ANother for you.
http://pastebin.com/6HDgjCN5

cmdline was:
/EyeWitness.py -f ingram.txt --threads 100 -d /var/www/asdf --results 100 --no-prompt --all-protocols -t 20

**Comment by ChrisTruncer** [comment]
@Viss - you happen to have a public URL that can cause that crash on you?

**Comment by Viss** [comment]
Internal scan for a client :\
I bet I could come up with something via shodan though..

**Comment by Viss** [comment]
oh, I should mention - when I did '--web' and not '--all-protocols' the problem went away. I figure it has something to do with either rdp or vnc.

**Comment by ChrisTruncer** [comment]
Oh, ok.  That's really good to know.  I thought it would be a web issue based off of the code.  There's odd issues at times when running all protocols.  I'll end up closing this out for the time being.  The work around really is just, at the moment, run different scans for each protocol.
