### ISSUE TITLE
errors when parsing a page

### ISSUE THREAD

**Issue by Viss** [ChrisTruncer/EyeWitness#149]
It was hitting a dell equal logic array mgmt login page and it popped a popup for 'your java is out of date'.
I can provide the source html if you'd like.

Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 294, in worker_thread
    cli_parsed, http_object, driver)
  File "/root/tools/EyeWitness/modules/selenium_module.py", line 91, in capture_host
    tempua = driver.execute_script("return navigator.userAgent")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 423, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 169, in check_response
    raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
UnexpectedAlertPresentException: Alert Text: Group Manager requires Java SE 6 Update 31 or later. Would you like to update now?
<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 294, in worker_thread
    cli_parsed, http_object, driver)
  File "/root/tools/EyeWitness/modules/selenium_module.py", line 91, in capture_host
    tempua = driver.execute_script("return navigator.userAgent")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 423, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 169, in check_response
    raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
UnexpectedAlertPresentException: Alert Text: Group Manager requires Java SE 6 Update 31 or later. Would you like to update now?
<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>

**Comment by Viss** [comment]
page source:

```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--
   Copyright (c) 2002-2013 by Dell Inc.

   All rights reserved.  This software may not be copied, disclosed,
   transferred, or used except in accordance with a license granted
   by Dell Inc.  This software embodies proprietary information
   and trade secrets of Dell Inc.
-->

<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <title>EqualLogic Group Manager</title>
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

    <style type="text/css">
      body
      {
        padding: 100px;
        font-family: Arial, sans-serif;
        text-align: center;
      }

      #logo
      {
        text-align: center;
      }

      h2
      {
        color: #808080;
        text-align: center;
      }

      #LaunchInfo
      {
        text-align: center;
      }

      #LaunchInfo a
      {
        font-family: Arial, sans-serif;
        display: block;
        font-size: 18px;
        font-weight: bold;
        text-decoration: none;
        margin: 10px auto 10px auto;
        padding: 5px;
        border: 2px solid #000;
        background: #333333;
        color: #FFF;
        width: 275px;
      }

      #LaunchInfo a:hover
      {
        background: #CCCCCC;
        color: #000000;
      }

      .error
      {
        margin: 20px auto 25px auto;
        width: 400px;
        min-height: 32px;
        background: url('warning.png') top left no-repeat;
        padding-left: 50px;
        color: #660000;
        text-align: left;
        font-size: 20px;
        display: none;
      }

      .error-detail
      {
        font-size: 16px;
      }
    </style>

    <script type="text/javascript">
      var error = null;
      if (location.href.indexOf('?') > 0)
      {
        error = location.href.substring((location.href.indexOf('err=') + 4), location.href.length);
      }

      window.onload = function()
      {
        if (error != null)
        {
          document.getElementById(error).style.display="block";
        }
      }

    </script>
  </head>

  <body>
    <div id="logo">
      <img src="/logo.png">
    </div>

    <h2>EqualLogic Group Manager</h2>

    <div class="error" id="Duplicate_Gui_Session">
      Another GUI session to the same group has been detected
      on your machine. Only one GUI session to the group is
      allowed from a single client machine.
    </div>

    <div class="error" id="No_Privileges">
      You did not grant running privileges to the Group Manager applet.
    </div>

    <div class="error" id="Old_Java">
      Group Manager requires Java SE 6 Update 31 or later.
      <div class="error-detail">
        <a href="http://www.java.com/en/download/manual.jsp">Download the latest Java plug-in.</a>
      </div>
    </div>

    <div class="error" id="Old_Java_OSX">
      Group Manager requires Java SE 7 Update 21 or later.
      <div class="error-detail">
        <a href="http://www.java.com/en/download/manual.jsp">Download the latest Java plug-in.</a>
      </div>
    </div>

    <div class="error" id="Idle_Timeout">
      You have been logged out due to inactivity.
    </div>

    <div class="error" id="Download_Failed">
      Group Manager download failed.
    </div>

    <div class="error" id="Browser_Incompatible">
      Group Manager is not compatible with this web browser.
    </div>

    <div id="LaunchInfo" >
      <a href="index.html">Launch in browser window</a>
      <a href="groupmgr.jnlp">Launch as an application</a>
    </div>

  </body>
</html>
```

**Comment by Viss** [comment]
Looks like there's something that can make the parser choke:

```
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 294, in worker_thread
    cli_parsed, http_object, driver)
  File "/root/tools/EyeWitness/modules/selenium_module.py", line 91, in capture_host
    tempua = driver.execute_script("return navigator.userAgent")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 423, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 169, in check_response
    raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
UnexpectedAlertPresentException: Alert Text: This page is asking you to confirm that you want to leave - data you have entered may not be saved.
<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>
```

**Comment by rvazarkar** [comment]
I'll push a solution to this soon. Shouldn't be a hard fix

**Comment by rvazarkar** [comment]
This should be fixed. I had a driver command outside of exception checking, silly me

Luckily, its not a page parsing issue =)
