### ISSUE TITLE
Search report - links incorrect

### ISSUE THREAD

**Issue by schristiaens** [ChrisTruncer/EyeWitness#150]
When generating a report from Search.py, the "page 1", "page 2", etc links still point to "report_pageX.html" instead of "search_pageX.html".  This makes navigation difficult.  I know it is an easy fix, but can't get to it very soon, so I figured I would log it.

**Comment by ChrisTruncer** [comment]
Ok,

That will be a quick fix for us. Sorry about that, but thanks for reporting it to us. Is this only on web reports?

**Comment by schristiaens** [comment]
I've had other troubles running RDP and VNC reports, so I'm not sure.  I
will file a separate issue with the details.

Thanks for a great tool, it saves me a ton of time and I hope to be able to
contribute more than just issues at some point.

**Comment by ChrisTruncer** [comment]
looking into this now

**Comment by ChrisTruncer** [comment]
Just pushed the fix.  This should be good now.  Thanks for reporting it!
