### ISSUE TITLE
wrong copy on scan start

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#155]
I've just started a scan based on nmap results, the first line is:

```
Starting Web Requests (70 Hosts)
```

But this is wrong, there are only 40 hosts but 70 ports to check. You have similar during the scan

```
[*] Completed 15 out of 70 hosts
```

maybe change hosts to services.

**Comment by ChrisTruncer** [comment]
Thanks, yeah that's probably worth changing and clarifying. I'll look into this shortly.

**Comment by digininja** [comment]
You might be able to work out x hosts and y services.

**Comment by ChrisTruncer** [comment]
Just changed this to "services" for the time being.  Once I move and have some dev cycles to this, I can look into changing the output by hosts and services.

Thanks for letting us know about this.
