### ISSUE TITLE
--createtargets requires a protocol

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#156]
The --createtargets option requires a protocol but then ignores it and dumps out everything found - at least it does when I give it an nmap file of web servers and specify RDP.

**Comment by ChrisTruncer** [comment]
Ah... good find on this.  This will be a little bit of an issue.  I'll get looking at this.

**Comment by ChrisTruncer** [comment]
Just got this fix merged in.  Thanks for letting me know!
