### ISSUE TITLE
silverlight [enhancement idea]

### ISSUE THREAD

**Issue by ebrinkster** [ChrisTruncer/EyeWitness#159]
Any chance to test out silverlight compatibility?  I've tried it on Linux in the past with mixed results.  May be easy to integrate into mono and selenium.  It's a fringe case, but I sometimes run into it.

**Comment by rvazarkar** [comment]
If it works in your Firefox browser, it should work out of the box with
--web

**Comment by ChrisTruncer** [comment]
Let us know if it works, I'll close for now
