### ISSUE TITLE
report section for secure connection failed

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#162]
I don't know if you can detect this but having a report section for what Firefox labels "Secure Connection Failed" would be good.

**Comment by ChrisTruncer** [comment]
Hm.. does it have anything for source code, maybe just a HTML tag with a title in it?

**Comment by digininja** [comment]
EyeWitness gets some source back but its from the browser not the site so
might not be that good to go off. I'll mail you what I got.

**Comment by ChrisTruncer** [comment]
Is this what is included in the report when you click on the "source code" link for that item?  If it is, then I should be able to make a signature/section for this.

**Comment by digininja** [comment]
Yes but does that depend on the browser that is being used?

**Comment by ChrisTruncer** [comment]
Yeah, it will.  For now, I've committed some code based off of a browser's sample (what was sent).  If you encounter this with other browsers, let me know and I can get it added in too.

**Comment by ChrisTruncer** [comment]
Thanks for sending that my way
