### ISSUE TITLE
HTTPS from list input

### ISSUE THREAD

**Issue by jhaddix** [ChrisTruncer/EyeWitness#165]
Hey all! 

First of, LOVE the project. Just tried it out. Epic.

One use case I wanted to know if if you could add would be a a "try HTTPS" option to list input. Let me go over the use case for me here:

Using tools like recon-ng I end up with a list of domains and subdomains scraped from google, shodan, bruteforced, etc. The issue here is that recon-ng and most tools only identify DNS entries and not protocol that the site might be over. When providing a vanilla list of hosts to EyeWitness without a protocol it seemed just to query them all over HTTP, whereas it would be lovely if it tried HTTP AND HTTPS for each line in that list. Would that be possible?

**Comment by digininja** [comment]
An option for you would be to use nmap to check for ports 80 and 443 on all
those hosts and then feed the nmap XML file into eyewitness. There is an
extra step but OK as a work around.

**Comment by jhaddix** [comment]
Yeah was trying to avoid that but no worries if i need to do it =)

**Comment by digininja** [comment]
Trying to send as little traffic as possible?

**Comment by jhaddix** [comment]
That's one case, yes. Also, nmap can be identified in some cases.

**Comment by digininja** [comment]
Other option is to just create the file,l and duplicate it with https in
the second half.

**Comment by jhaddix** [comment]
i just did that with a 1liner! Seems my case is covered just by not being lazy =P Thanks for the comms, i'll just script everything up =) feel free to close.

**Comment by ChrisTruncer** [comment]
Hm... So, it isn't necessarily a bad idea.  We had originally just put http since that is what most sites at the time used.  Granted, most probably now still use http, but there's a lot more with https as well.  Would you all think it's worth adding it in to do both http and https by default, have a switch to do both http and https, or leave it as is currently?

I'm willing to do whatever would be the most useful, and I could go any of those three ways.

**Comment by jhaddix** [comment]
A switch would work fine for me. I'm using this for external web testing against large orgs, which has a higher chance to present only HTTPS sites since they are on the web (although some still are web portals offering a self signed cert).

**Comment by jhaddix** [comment]
Also, one reason i want to avoid nmap is that it doesn't honor virtualhosts and redirects. Nmap treats all my domains and resolves them to IPs , then scans for web ports. In the real world, using a browser, many applications can be hosted on the same IP using virtualhosts.

**Comment by digininja** [comment]
I think honour what is asked for which would be http by default but a flag
as suggested to do both would probably be useful.

**Comment by jhaddix** [comment]
My previous comment is actually a huge thing I think most pentesters miss FYI:

NameVirtualHost *:80			
  ServerName vh1.example.com
  DocumentRoot /var/www/vhosts/vh1
</VirtualHost>

<VirtualHost *:80>			
  ServerName vh2.example.com
  DocumentRoot /var/www/vhosts/vh2
</VirtualHost>


These are both just port 80 to nmap, but there are two applications here... could be hundreds on a single server. Hence requesting with a browser, the vhosts are honored (and redirects) and you will not miss anything.

**Comment by digininja** [comment]
I find The Harvester is good at creating lists for vhost names.

**Comment by jhaddix** [comment]
Yeah, its just scraping using Bing's operators though. Recon-ng and my script enumall.sh will scrape all major search engines (bing, yahoo, google, baidu), plus netcraft and shodan: https://github.com/jhaddix/domain

**Comment by digininja** [comment]
I'll give your script a try

**Comment by jhaddix** [comment]
I'll update it, have made some changes since the version on github  =P

**Comment by ChrisTruncer** [comment]
I'm pretty sure I have this set, doing some final tests before a merge

**Comment by jhaddix** [comment]
Thanks Chris!  One thing you might run into is having to accept self signed certs with your browse with selenium, to get a proper screenshot.

**Comment by ChrisTruncer** [comment]
Merged this in.  Just use --prepend-https now and it will add both http:// and https:// in front of any URL which doesn't start with either one of those.

As for the self-signed certs, I believe that it should already be able to handle self-signed certs.  If that isn't the case and you run across a URL where you're having issues, just let me know and I'll be happy to look into it.

**Comment by digininja** [comment]
Self-signed certs have been fine for me.
