### ISSUE TITLE
Bruteforcing Services

### ISSUE THREAD

**Issue by jhaddix** [ChrisTruncer/EyeWitness#167]
Is the next logical progression doing something like https://github.com/1N3/BruteX/blob/master/brutex ? or is EW staying recon only?

**Comment by ChrisTruncer** [comment]
I think we're probably mostly going to be a recon tool, but we will definitely be adding in the ability to attack some services.  For example, @rvazarkar is currently working on adding a tomcat brute forcer to go along with EyeWItness.

The thing is, there's already tons of other brute forcers out there, so unless we felt we could do a better job, or wanted to learn by writing a brute forcer ourselves, we may leave it to the other tools.

But with all that said, if there's a compelling reason why something should be added in to EyeWitness, we're always open ears to consider it.

**Comment by digininja** [comment]
Maybe do like Nessus does and have a section to say what it is brute
forcible with.

Or links to articles about the site or product.

**Comment by ChrisTruncer** [comment]
I'll put this on a shared document, but for now I'm going to go ahead and close it out.  The only services we're really currently looking at would be http(s), rdp, and vnc.  As we get into additional services, then this will come into play and we can do that.

Thanks for the suggestion.
