### ISSUE TITLE
Show default creds at the top

### ISSUE THREAD

**Issue by ChrisTruncer** [ChrisTruncer/EyeWitness#168]
If default creds are identified, lets potentially list them near the top like we do for categories.

What's your thoughts @rvazarkar?

**Comment by digininja** [comment]
You mean have a category for devices you know creds for? Or are you
planning to start trying to see if they have default creds enabled?

**Comment by ChrisTruncer** [comment]
I was debating having an area at the beginning of the report that may directly link to a device that hit a signature for default creds.  My only concern is that it may get too cluttered, and I might just want to leave it as is where instead of also calling out at the top of a report, it's just listed for each "row" in the report.

I'm kind of going back and forth, and now I'm leaning to just leave it as is to prevent clutter.

**Comment by digininja** [comment]
Maybe highlight them in some way but I don't think having their own
category is worth it.

**Comment by ChrisTruncer** [comment]
agreed. For now, I'll close this out, like you said, probably isn't worth it currently.
