### ISSUE TITLE
tor / socks proxy support?

### ISSUE THREAD

**Issue by Viss** [ChrisTruncer/EyeWitness#170]
so fun fact - after you scan the shit out of some places, they block you.
it makes the screenshotting afterwards difficult. I've tried to push eyewitness through tor, but it doesn't work...

![image](https://cloud.githubusercontent.com/assets/1756255/12935503/f5a8c39c-cf4a-11e5-892e-031dc3a8212a.png)

nor does specifying tor as a proxy, all I get are screenshots of the tor error saying 'im not an http proxy, go away'.

halp?

**Comment by Viss** [comment]
that error was from this cmdline

>  xvfb-run sudo torsocks ./EyeWitness.py --web -f file.xml

**Comment by ChrisTruncer** [comment]
Does --headless work instead of --web?

**Comment by Viss** [comment]
![image](https://cloud.githubusercontent.com/assets/1756255/12937048/6941cd5e-cf59-11e5-8c47-86b12eae763b.png)

whoooo! nope :D

**Comment by ChrisTruncer** [comment]
Damn,

Unfortunately, I might not be able to get it going. It's likely going to be compatibility with the libraries I'm using for screenshots/connecting to websites.  I'll see if there's any features in them now, but likely this is something that will have to be submitted upstream to selenium and phantoms (unfortunately) vs. me being able to add it in.

But I'll take a look and see if I see anything.

**Comment by Viss** [comment]
Righton, no worries :D

**Comment by digininja** [comment]
Could you use proxychains or Burp as an intermediate? Have Eyewitness talk
to something it can and have that app talk to Tor.

**Comment by Viss** [comment]
I'm trying to scan entire countries, and push results through
eyewitness, so sadly I need something that won't die on me part of the
way through - burp cant handle that sort of volume, sadly

**Comment by digininja** [comment]
What about proxychains?

**Comment by ChrisTruncer** [comment]
I'll close this for now since I don't believe that I can get this implemented until the libraries support it.  Once they do, then this will probably work
