### ISSUE TITLE
No support for unicode urls

### ISSUE THREAD

**Issue by shayster01** [ChrisTruncer/EyeWitness#179]
Tried cyrillic urls and did not translate urls correctly. 

Example:
http://сео-сегодня.рф

Showed up as :
http://ÑÐµÐ¾-ÑÐµÐ³Ð¾Ð´Ð½Ñ.Ñ€Ñ„/

**Comment by ChrisTruncer** [comment]
hm... you're right.  I'm going to have to look into this.

Thanks

**Comment by ChrisTruncer** [comment]
Can you provide a valid URL to connect to?  When trying to connect to that in Firefox I'm getting an error.

**Comment by shayster01** [comment]
I have officiated the url with [ ].

http://сео-сегодня <http://xn----ftbdbb4ccdvd3n>[.]рф/

Regards,
Shawn

**Comment by ChrisTruncer** [comment]
At the moment, I can't seem to get this working.  If you have any suggestions, I'm all ears, otherwise I'll have to keep looking at this when i can.

**Comment by ChrisTruncer** [comment]
For now, I'm going to close this out.  If you or anyone else wants to add this in, feel free to send a pull request.
