### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by gettingstarted247** [ChrisTruncer/EyeWitness#183]
**OS Used -** Linux kali-2016 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux

**Error:  **
################################################################################
#                                  EyeWitness                                  #
################################################################################

Traceback (most recent call last):
  File "./EyeWitness.py", line 576, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 392, in multi_mode
    dbm.create_vnc_rdp_object('rdp', rdp, cli_parsed)
  File "/home/user/git-repos/EyeWitness/modules/db_manager.py", line 165, in create_vnc_rdp_object
    port = int(port)
ValueError: invalid literal for int() with base 10: '///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>\n'

**Expected behavior **- Eyewitness worked flawlessly the first time, now subsequent attempts to use the tool produces the above error

**Any additional information** - command line used: ./EyeWitness.py --all-protocols -f ~/nmap.xml
Any ideas????

**Comment by ChrisTruncer** [comment]
It looks like it thinks there is something off with your XML file.  Did you resume your XML scan at all vs. letting it finish all at once?  Resuming can lead to malformed XML.  One thing you can try, is switching to the "SAX" branch and use that.  It's about to get merged into EyeWitness in a few days, and it's a different way to parse xml. Just use the -x option to provide the XML file.

But my guess is it is likely the XML itself is the problem based on the error.

**Comment by gettingstarted247** [comment]
Thank you, Chris.  That is exactly what it was.  Didn't even cross my mind that it could be malformed.  Appreciate the quick response!

**Comment by ChrisTruncer** [comment]
not a problem at all
