### ISSUE TITLE
Unable to connect to X Server

### ISSUE THREAD

**Issue by garethgtt** [ChrisTruncer/EyeWitness#185]
Debian Jessie

Using this on both VNC and RDP getting the following error

Starting VNC/RDP Requests (11 Hosts)
EyeWitness.py: cannot connect to X server

**Comment by ChrisTruncer** [comment]
Is this being run headlessly?

**Comment by ChrisTruncer** [comment]
I'm not at a place where I can get a good internet connection, so it might be a while before I can download and make an image.

Have you had the chance to look at the issue at all and maybe have any insights? I'll be sure to check them out.

**Comment by garethgtt** [comment]
Hi Yes this is being run Headlessly on an external VPS.

**Comment by ChrisTruncer** [comment]
So that's going to be the problem.  I believe your best bet would be to run an X server locally and do X-11 forwarding through your SSH tunnel.

Or run EyeWitness in a local instance (VM?).  It just looks like the library where I can for VNC or RDP don't support headless operation.
