### ISSUE TITLE
mac rather than ipv4 address being read from nmap xml

### ISSUE THREAD

**Issue by cybergibbons** [ChrisTruncer/EyeWitness#187]
OS: Linux kali 3.18.0-kali3-586 #1 Debian 3.18.6-1~kali2 (2015-03-02) i686 GNU/Linux (Offsec VM used for PWK), but also a later version fully up to date.

New XML parser seems to be taking the MAC address rather than IPv4. Easy to temporarily resolve using grep to cut those lines:
`grep -v 'addrtype=\"mac\"' web.xml > web_ew.xml`

### Start of nmap.xml
```
<?xml version="1.0"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>
<!-- Nmap 6.47 scan initiated Wed May 11 00:04:21 2016 as: nmap -p80,443 -oA /root/labs/nmap/web 10.11.1.0/24 -->
<nmaprun scanner="nmap" args="nmap -p80,443 -oA /root/labs/nmap/web 10.11.1.0/24" start="1462921461" startstr="Wed May 11 00:04:21 2016" version="6.47" xmloutputversion="1.04">
<scaninfo type="syn" protocol="tcp" numservices="2" services="80,443"/>
<verbose level="0"/>
<debugging level="0"/>
<host starttime="1462921461" endtime="1462921464"><status state="up" reason="arp-response" reason_ttl="0"/>
<address addr="10.11.1.5" addrtype="ipv4"/>
<address addr="00:50:56:89:64:4E" addrtype="mac" vendor="VMware"/>
<hostnames>
</hostnames>
<ports><port protocol="tcp" portid="80"><state state="closed" reason="reset" reason_ttl="128"/><service name="http" method="table" conf="3"/></port>
<port protocol="tcp" portid="443"><state state="closed" reason="reset" reason_ttl="128"/><service name="https" method="table" conf="3"/></port>
</ports>
<times srtt="160310" rttvar="91340" to="525670"/>
</host>

```
### Running:
`EyeWitness.py --web -x web.xml`

### Output:
```
################################################################################
#                                  EyeWitness                                  #
################################################################################

Starting Web Requests (38 Hosts)
Attempting to screenshot http://00:50:56:89:64:24
[*] WebDriverError when connecting to http://00:50:56:89:64:24
Attempting to screenshot https://00:50:56:89:64:24
[*] WebDriverError when connecting to https://00:50:56:89:64:24
Attempting to screenshot http://00:50:56:89:45:BA






```

**Comment by ChrisTruncer** [comment]
How did you run your nmap scan (what command line options did you give)?


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer

On May 11, 2016 at 2:15:08 AM, cybergibbons (notifications@github.com) wrote:

OS: Linux kali 3.18.0-kali3-586 #1 Debian 3.18.6-1~kali2 (2015-03-02) i686 GNU/Linux (Offsec VM used for PWK), but also a later version fully up to date.

New XML parser seems to be taking the MAC address rather than IPv4. Easy to temporarily resolve using grep to cut those lines:
grep -v 'addrtype=\"mac\"' web.xml > web_ew.xml

Start of nmap.xml

<?xml version="1.0"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>















Running:

EyeWitness.py --web -x web.xml

Output:

################################################################################

EyeWitness

################################################################################

Starting Web Requests (38 Hosts)
Attempting to screenshot http://00:50:56:89:64:24
[] WebDriverError when connecting to http://00:50:56:89:64:24
Attempting to screenshot https://00:50:56:89:64:24
[] WebDriverError when connecting to https://00:50:56:89:64:24
Attempting to screenshot http://00:50:56:89:45:BA

**Comment by cybergibbons** [comment]
Will update it shortly - must have been trimmed out of issue for some reason.

**Comment by ChrisTruncer** [comment]
Thanks.  I did just test a NMap scan running it as:

nmap -vvv --open -p- -Pn -n -oA testnmapout -A -iL <inputfile>

I used the xml output and I parsed the IP address correctly, so the main reason I am asking for how you ran the scan is to look at that output and figure out if I need to provide any sort of mods to my parser based on the output.

**Comment by cybergibbons** [comment]
Ah, if you go to the page (not the email) it has the full command:

nmap -p80,443 -oA /root/labs/nmap/web 10.11.1.0/24

Local network, so will have MAC addresses, which might be the difference.

On 11 May 2016 at 15:35, ChrisTruncer <notifications@github.com> wrote:

> How did you run your nmap scan (what command line options did you give)?
>
>
>
> -----------------------------------------------------------------------------------------
> Christopher Truncer
> @christruncer
>
> On May 11, 2016 at 2:15:08 AM, cybergibbons (notifications@github.com)
> wrote:
>
> OS: Linux kali 3.18.0-kali3-586 #1 Debian 3.18.6-1~kali2 (2015-03-02) i686
> GNU/Linux (Offsec VM used for PWK), but also a later version fully up to
> date.
>
> New XML parser seems to be taking the MAC address rather than IPv4. Easy
> to temporarily resolve using grep to cut those lines:
> grep -v 'addrtype=\"mac\"' web.xml > web_ew.xml
>
> Start of nmap.xml
>
> <?xml version="1.0"?>
> <!DOCTYPE nmaprun>
> <?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl"
> type="text/xsl"?>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> Running:
>
> EyeWitness.py --web -x web.xml
>
> Output:
>
>
> ################################################################################
>
> EyeWitness
>
>
> ################################################################################
>
> Starting Web Requests (38 Hosts)
> Attempting to screenshot http://00:50:56:89:64:24
> [] WebDriverError when connecting to http://00:50:56:89:64:24
> Attempting to screenshot https://00:50:56:89:64:24
> [] WebDriverError when connecting to https://00:50:56:89:64:24
> Attempting to screenshot http://00:50:56:89:45:BA
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisTruncer/EyeWitness/issues/187#issuecomment-218478674>
>



-- 
Andrew

**Comment by ChrisTruncer** [comment]
Yup, you were right.  This only happened when scanning a system where NMap can identify the MAC address.  Thanks for pointing this out.  The patch was just merged in.

**Comment by cybergibbons** [comment]
Awesome, thanks for dealing with that.

On 12 May 2016 at 03:49, ChrisTruncer <notifications@github.com> wrote:

> Yup, you were right. This only happened when scanning a system where NMap
> can identify the MAC address. Thanks for pointing this out. The patch was
> just merged in.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisTruncer/EyeWitness/issues/187#issuecomment-218646194>
>



-- 
Andrew

**Comment by ChrisTruncer** [comment]
Not a problem at all.  thanks for letting me know
