### ISSUE TITLE
Kali Rolling setup script addition

### ISSUE THREAD

**Issue by sopsmattw** [ChrisTruncer/EyeWitness#188]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali-Rolling

## Pastebin link to error you are encountering
"RDP libraries are not installed" in rdp_modules.py but the root error is one of the imports yields "cryptography.hazmat.bindings.openssl.binding" error.

## Expected behavior (vs. what you encountered)
Fresh Kali install from 2016.1 iso

## Any additional information
the setup script should include the following lines 

apt-get install python-openssl libssl-dev
pip install cryptography

**Comment by ChrisTruncer** [comment]
Hey there,

I just tested the setup script (which hasn't been modified in some time) on both Kali rolling and Debian, and both installed correctly.  I'm also able to successfully screenshot RDP servers with EyeWitness.  

If you can find anything wrong, I'd be happy to look into it further, but for now I think it might have been a weird issue with the install on your system.

**Comment by sopsmattw** [comment]
ok.. Thanks for the quick response.. Once I finish this pentest, I'll build another quick VM and try again.. I'm using the "light" version as well, if that makes a difference. Base install so the client has a small download. incredibly awesome tool, by the way..

**Comment by ChrisTruncer** [comment]
Ah, that will probably be the reason.  We're really targeting the standard image of Kali, so a light version might be missing some libraries.

**Comment by wifiuk** [comment]
i can confirm the script doesnt install the RDP files needed, using Kali also in Virtualbox, the script doesnt error that i can see.

Says RDP libraries not found
Please run the script in the setup directory.

**Comment by wifiuk** [comment]
actually did get errors

```
[*] Installing RDPY
Cloning into 'rdpy'...
remote: Counting objects: 2595, done.
remote: Total 2595 (delta 0), reused 0 (delta 0), pack-reused 2595
Receiving objects: 100% (2595/2595), 892.06 KiB | 554.00 KiB/s, done.
Resolving deltas: 100% (1624/1624), done.
Checking connectivity... done.
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/test-easy-install-2135.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).


```

**Comment by wifiuk** [comment]
needed to run setup as Sudo, fixed the issues
