### ISSUE TITLE
Modulize EyeWitness

### ISSUE THREAD

**Issue by Den1al** [ChrisTruncer/EyeWitness#195]
Are there any plans to modulize Eyewitness as for using in other python scripts?

**Comment by ChrisTruncer** [comment]
Not really at the moment.  Right now it's more of a stand-alone tool.  Is there anything specific you were looking for?

**Comment by Den1al** [comment]
Actually yes.
I was looking for a way to automize your code and harness it inside another
code.

2016-07-12 18:01 GMT+03:00 ChrisTruncer <notifications@github.com>:

**Comment by ChrisTruncer** [comment]
OK,

Well thanks for the interest.  At the moment though, I don't really have the time, but moreso the plans, to modularize this.  I've planned on keeping EyeWitness more of its own stand-alone tool.  If anything changes, I'll be sure to post back in here, but for now I plan to keep it as is.

Thanks for the interest!
