### ISSUE TITLE
Auto-Recognize HTTP -> HTTPS errors

### ISSUE THREAD

**Issue by securitygeneration** [ChrisTruncer/EyeWitness#197]
Sometimes a server will respond with a 400, stating that an HTTP request was made to a port that's expecting HTTPS, but doesn't perform an on-page redirect (see screenshot). EyeWitness could recognize this text (or a hash of the entire page), and auto-redirect to HTTPS.

<img width="316" alt="bad request" src="https://cloud.githubusercontent.com/assets/1046239/16869284/64799d3a-4a7c-11e6-91f1-638ecd9516de.png">

**Comment by ChrisTruncer** [comment]
This is a good idea, but I don't really have the ability to detect if it is a HTTPS port by the error code.  I don't believe that a 400 automatically means that there is a HTTPS listener (vs. http), so I don't want to program in to auto-try it without a means to know for sure.

**Comment by securitygeneration** [comment]
I'm not suggesting recognising based on error code. As you correctly state, a 400 simply means there was a bad request. But in this case, the server is specifically telling us that we're making an HTTP request to an SSL-enabled port, we'd be silly not to listen. You _could_ recognise the page body (or hash thereof), and thus repeat the request with SSL. Otherwise, in its current form, there is no way that EyeWitness will be able to reach the website to screenshot.
