### ISSUE TITLE
Specific HTTPS ports?

### ISSUE THREAD

**Issue by securitygeneration** [ChrisTruncer/EyeWitness#198]
In order to deal with #197, I tried using both --prepend-https and --add-https-ports on the ports that required HTTPS. This seemed to have no effect, and EW continued to request those pages as HTTP. Am I doing it wrong? The input was an nmap XML file (which I think recognised those ports as speaking HTTPS).

**Comment by ChrisTruncer** [comment]
So, it looks like I removed the --add-http-ports and --add-https-ports switches when switching over to the new XML parsing mode.  I'll look to see if I am able to get it added back in based on how I am doing the parsing.

However, that is only used, along with the --prepend-https switch, when using file input with each URL on a new line.  When providing XML input, it's ignored and uses the XML file.

As long as the nmap xml file detects the service, it should be able to make a determination if it is http or https.  The only way it wouldn't is if there's a http server on 443 or 8443, or https server on 80 or 8080.  Outside of that, it will detect if there's http or https running.

This is done here for nmap - https://github.com/ChrisTruncer/EyeWitness/blob/54a17d385888ffceadaa7ff6560280a2956e9fc4/modules/helpers.py#L60-L66
