### ISSUE TITLE
Only scan certain ports

### ISSUE THREAD

**Issue by securitygeneration** [ChrisTruncer/EyeWitness#199]
It would be nice to have an --only-ports option that allows us to define which specific ports we want to scan (i.e. --only-ports 80,443,8080), instead of using the standard portlist that EW will try by default.

**Comment by ChrisTruncer** [comment]
I can probably get this added in.  It would only apply to input via a file (not XML input).

**Comment by ChrisTruncer** [comment]
Well, before I put this in, what's the use case why you would need to specify this?  At the moment, it seems a little extraneous.  If generating a file yourself with a URL on each newline, wouldn't this information already be in here?  And if using XML input, it will auto-parse the file and find all systems on all ports.  If you need the XML info to only pull out web servers listening on certain ports, couldn't the scan be configured to only look for those?

Unless there's a situation I am not thinking of, I think this might be a niche request where it could be better handled prior to using EyeWitness, but I am all ears to hear your/any thoughts on this.

**Comment by securitygeneration** [comment]
Indeed, this would be extraneous when providing a file with URLs. I actually find this to be most useful when providing an XML file. During penetration testing, you tend to run fairly large scans, some of which can take a while, and you then use those as a source for a number of things. I would much rather just be able to tell EyeWitness to only scan certain ports in that XML file instead of having to either a) re-run a new scan with only the ports I want, or b) play around with my nmap output in order to create a file with a single URL/IP/port per line (and have to do that each time I want to run a separate EyeWitness scan for a new port).

**Comment by securitygeneration** [comment]
Although after thinking about it, even though it's a bit more extraneous for a URL file, I'd still like to see this as a global option. I could definitely see myself having a list of IPs (say a bunch of IPs in scope for a test), and be able to tell EyeWitness to only scan ports 80, 443 and 8080. Yes, in reality I'd probably portscan those IPs as well, but if this option exists, I see no reason why not have it globally.

**Comment by ChrisTruncer** [comment]
This has now been merged in, hope it helps!

**Comment by securitygeneration** [comment]
Beautiful, thanks Chris! 👍

**Comment by ChrisTruncer** [comment]
No problem
