### ISSUE TITLE
HP printer listed as Uncategorized instead of Printers

### ISSUE THREAD

**Issue by leebaird** [ChrisTruncer/EyeWitness#206]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali rolling

Page Title: HP Officejet Pro 6830 e-All-in-One
content-length: 658
content-language: en
x-content-type-options: nosniff
content-encoding: gzip
set-cookie: sid=s5368ba0a-86ccbf597994fe0f5ee96063826a56cf;path=/;
server: HP HTTP Server; HP Officejet Pro 6830 - E3E02A; Serial Number: TH5196C0X3; Built:Mon Feb 29, 2016 09:46:24AM {PNP1CN1610AR}
last-modified: Mon, 29 Feb 2016 09:46:24 GMT
x-ua-compatible: IE=edge
cache-control: max-age=0
Response Code: 200
x-frame-options: SAMEORIGIN
content-type: text/html

**Comment by ChrisTruncer** [comment]
Are you able to provide a live site to test against?

If not, can you pastebin the source code to the webpage so we can write a signature?  Thanks!

**Comment by ChrisTruncer** [comment]
just merged this in
