### ISSUE TITLE
Apache default page listed as Unauthorized instead of Splash Pages

### ISSUE THREAD

**Issue by leebaird** [ChrisTruncer/EyeWitness#207]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali rolling

Page Title: Apache HTTP Server Test Page powered by CentOS
content-length: 4897
accept-ranges: bytes
server: Apache/2.4.6 (CentOS) PHP/5.4.16
last-modified: Thu, 16 Oct 2014 13:20:58 GMT
connection: close
etag: "1321-5058a1e728280"
date: Thu, 28 Jul 2016 14:11:08 GMT
Response Code: 403
content-type: text/html; charset=UTF-8 

Page Title: Apache HTTP Server Test Page powered by CentOS
content-length: 4897
accept-ranges: bytes
server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
last-modified: Thu, 16 Oct 2014 13:20:58 GMT
connection: close
etag: "1321-5058a1e728280"
date: Thu, 28 Jul 2016 14:11:11 GMT
Response Code: 403
content-type: text/html; charset=UTF-8

**Comment by ChrisTruncer** [comment]
Are you able to provide a live site to test against?

If not, can you pastebin the source code to the webpage so we can write a signature?  Thanks!

**Comment by ChrisTruncer** [comment]
added this in
