### ISSUE TITLE
Installation path for phantomjs has changed?

### ISSUE THREAD

**Issue by Viss** [ChrisTruncer/EyeWitness#211]
tl;dr, looks like your installer will need to pick up phantomjs from a new place: 

![image](https://cloud.githubusercontent.com/assets/1756255/17944584/4127ebbe-69f5-11e6-8616-773dc1cd1eaa.png)

**Comment by ChrisTruncer** [comment]
Unfortunately, it hasn't changed.  It might be they are doing blocks on too many wgets getting that resource.  I might try setting a user-agent and see if it helps

**Comment by ChrisTruncer** [comment]
Hopefully, this should help, but the path is still the same.
