### ISSUE TITLE
Crash on nmap import

### ISSUE THREAD

**Issue by zer0-t** [ChrisTruncer/EyeWitness#214]
Hi ChrisTruncer,

Tried to run EyeWitness with the nmap file import option.
And it crashes, I guess the nmap.xsl template changed.
See the pastebin link for more information.

Thanks!

## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux 2016.1
EyeWitness (used the latest commit 8f79bdb)

## Pastebin link to error you are encountering
http://pastebin.com/8mBqx0kC

## Expected behavior (vs. what you encountered)
RDP screenshot output

## Any additional information
Running EyeWitness with the option --rdp and the .xml input of nmap gives a ValueError: invalid literal for int()

**Comment by zer0-t** [comment]
Made an option mistake my bad

**Comment by ChrisTruncer** [comment]
No worries!
