### ISSUE TITLE
--createtargets flag not working

### ISSUE THREAD

**Issue by fir3d0g** [ChrisTruncer/EyeWitness#216]
When running the script with the --createtargets targets.txt flag, the command completes, but no targets list is created. This was attempted with all five (5) types (--all-protocols, web, rdp, vnc, and headless), and with both Nessus and Nmap files. 

Command example:
./EyeWitness.py -f nmap_a.xml --rdp --createtargets targets.txt

Thanks for an awesome tool!

**Comment by chango77747** [comment]
The input file for --createtargets needs to be a .nessus or .xml file output from Nmap or Nessus.


Kindest Regards,
Evan Pena
________________________________

**Comment by Raikia** [comment]
> ./EyeWitness.py -f nmap_a.xml --rdp --createtargets targets.txt

This should be:
./EyeWitness.py -x nmap_a.xml --rdp --createtargets targets.txt

![image](https://cloud.githubusercontent.com/assets/18066499/18728379/9aa7823e-8012-11e6-85cd-a245d3220038.png)

**Comment by fir3d0g** [comment]
I completely missed that. Thanks for the heads up. And thanks again for such an awesome tool!
