### ISSUE TITLE
Auto detect vhost name from certificate CN and AltName

### ISSUE THREAD

**Issue by iwm911** [ChrisTruncer/EyeWitness#217]
sometimes different web services are running on the same IP address. 
in the case of HTTP traffic there is no definitive way to determine the vhostname (you can use some redirects header and such but its a bit complex).

in the case of SSL (HTTPS) its possible to enumerate the virtual host name easily by parsing the server certificate and obtain the certificate common name and alternative names.

using this method its possible to do several requests to the same server using different host header and get different responses from the server and by that enumerate more services.

The code will obviously have to remove all wildcards CN and AltNames, however it can help identify a substantial amount of services which is currently missed.

**Comment by ChrisTruncer** [comment]
Is this saying what it should do, or are you submitting the code to incorporate that?

**Comment by iwm911** [comment]
well i have wrote the code that extracts the certificate CN and AltNames with help from sslchecker

```python

class _GeneralName(univ.Choice):
    # Copied from https://github.com/theprincy/sslchecker
    # We are only interested in dNSNames. We use a default handler to ignore
    # other types.
    # TODO: We should also handle iPAddresses.
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('dNSName', char.IA5String().subtype(
            implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)
        )
        ),
    )


class _GeneralNames(univ.SequenceOf):
    # Copied from https://github.com/theprincy/sslchecker
    componentType = _GeneralName()
    sizeSpec = univ.SequenceOf.sizeSpec + \
        constraint.ValueSizeConstraint(1, 1024)


class CertificateExtractor(object):
    # Based on https://github.com/theprincy/sslchecker
    def __init__(self,ip,port=443):
        cert = ssl.get_server_certificate((ip, port))
        self.x509 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)

    def subject(self):
        return self.x509.get_subject().get_components()

    def cn(self):
        c = None
        for i in self.subject():
            if i[0] == b"CN":
                c = i[1]
        if type(c) == bytes:
            c = c.decode('utf-8')
        return c


    def altnames(self):
        altnames = [self.cn()]
        for i in range(self.x509.get_extension_count()):
            ext = self.x509.get_extension(i)
            if ext.get_short_name() == b"subjectAltName":
                try:
                    dec = decode(ext.get_data(), asn1Spec=_GeneralNames())
                except PyAsn1Error:
                    continue
                for i in dec[0]:
                    altnames.append(i[0].asOctets())
        if type(altnames) == bytes:
            altnames = altnames.decode('utf-8')
        return altnames

    def get_names(self):
        names = set()
        for name in self.altnames():
            if not name.startswith('*'):
                names.add(name)
        return names
```

**Comment by ChrisTruncer** [comment]
This is really awesome, but right now I have a lot of different things on my plate and don't have the cycles to get this added in myself. If this is something where you would want to submit a pull request, I would be happy to review it.

Thanks for taking the time to look into this.
