### ISSUE TITLE
Geckodriver PATH 

### ISSUE THREAD

**Issue by dwin999** [ChrisTruncer/EyeWitness#220]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali Rolling
## Error

Message: 'geckodriver' executable needs to be in PATH.
## Cause

I think it's due to the version of firefox ( using verison 49.01) not supporting the gecko driver used. 
## Fix

Grabbed the latest copy of geckodriver from https://github.com/mozilla/geckodriver/releases

Copied into /usr/sbin 

All works fine now

**Comment by fede333lago** [comment]
This solution has worked perfectly for me. Thank you

**Comment by ChrisTruncer** [comment]
I'll check this out, thanks!

**Comment by ChrisTruncer** [comment]
This should now be fixed.  Thanks!
