### ISSUE TITLE
WebDriverError when connecting to 

### ISSUE THREAD

**Issue by prajganesh123** [ChrisTruncer/EyeWitness#221]
I get an WebDriveError connecting error when I have self signed certs. It's works fine for regular websites and valid SSL. Any idea how to fix it?

**Comment by ChrisTruncer** [comment]
Can you give a site to test against?  EyeWitness should work against both self-signed and CA signed certs.

**Comment by ChrisTruncer** [comment]
I'm going to close this for now.  I tested against a site with a self-signed cert and it worked.  Also, I did not receive any of the required information when you create an issue, so I can't really troubleshoot this.

If you still have an issue with this, please open a new issue and then provide the information that's requested so I can help you troubleshoot this.

**Comment by ved009** [comment]
It might be an architecture issue. I got the same error while running it over ARM.
