### ISSUE TITLE
RDP screenshoting not working

### ISSUE THREAD

**Issue by kd4zay** [ChrisTruncer/EyeWitness#222]
## OS Used - ALL Information (architecture, linux flavor, etc.)

kali
## Expected behavior (vs. what you encountered)

seems to always get this error when trying to screenshot rdp
## Any additional information

![eyewitness-error](https://cloud.githubusercontent.com/assets/11742395/19734539/866cdf78-9b6d-11e6-8051-9dd5877d8db7.JPG)

**Comment by ChrisTruncer** [comment]
Can you give any additional information?  I just tested EyeWitness on Kali against a windows system and it was able to take a screenshot.

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard back on this
