### ISSUE TITLE
Feature request: Custom number of retries before failure/error

### ISSUE THREAD

**Issue by Junohea** [ChrisTruncer/EyeWitness#225]
I'm often seeing hosts in the "errors" section that I can resolve in a browser without issue. 
- Assuming network throttling: Adjusting the timeout/jitter/threads doesn't seem to help.
- Assuming browser issues: Modifying useragent/headless/etc. doesn't seem to help either.

Would love to see something like:
- Custom number of retries before it considers a host truly failed
- A flag that when enabled would asks the script to go back through all failed entries and try again X amount of times

The former is certainly a simpler broad-stroke approach, the latter is perhaps a bit too niche use-case.

**Comment by ChrisTruncer** [comment]
I just merged in the ability to specify the number of retries for timed out websites.  Hope this helps!
