### ISSUE TITLE
Setup script for Kali 2 doesn't execute

### ISSUE THREAD

**Issue by kuskumar** [ChrisTruncer/EyeWitness#227]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali GNU/Linux Rolling \n \l
## Pastebin link to error you are encountering
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7f657713a490>> ignored

## Expected behavior (vs. what you encountered)

While executing setup.sh, code for Kali 1 executes instead of executing Kali Rolling setup due to which geckodriver and kali2phontomjs needs to downloaded and manually installed.

## Any additional information

**Comment by ChrisTruncer** [comment]
Can you try Kali rolling?

**Comment by kuskumar** [comment]
Sorry I didn't get that, you mean should I try running Kali Rolling OS ? Your setup script grep for "Kali GNU/Linux Rolling \n \l" and if found true then set "osinfo" to true. In my case the first conditions sets to true but it does set "osinfo" to Kali2 due to which Kali2 case does not run.

**Comment by ChrisTruncer** [comment]
Sorry, I still don't understand.  Are you saying the setup script does not work on Kali Rolling?

**Comment by syllaibr64** [comment]
I have tested on Kali Rolling, I got the error in attached. 
![screen shot 2017-01-08 at 18 20 56](https://cloud.githubusercontent.com/assets/4463714/21751913/5e9ad2ce-d5cf-11e6-89f9-7a227cf73d75.png)

**Comment by rvazarkar** [comment]
You most likely downloaded the html version not raw if you're getting a
doctype error. Check the file and make sure it's not the html version of
the github page
