### ISSUE TITLE
Feature Request: Stickykeys/Utilman Backdoor Detection

### ISSUE THREAD

**Issue by 0x27** [ChrisTruncer/EyeWitness#229]
Seeing as the tool is already doing RDP screenshots, it might be interesting to add in something like this: [sticky keys slayer](https://github.com/linuz/Sticky-Keys-Slayer).

**Comment by ChrisTruncer** [comment]
Hey, thanks for the suggestion.  At the moment, EyeWitness doesn't do any sort of interaction with the RDP session that is created, it just screenshots the image.  At this moment, I don't plan on getting interaction added into it.  However, if someone were to create a pull request adding the feature, I would be happy to review it.
