### ISSUE TITLE
Message: 'geckodriver' executable needs to be in PATH. 

### ISSUE THREAD

**Issue by wifiuk** [ChrisTruncer/EyeWitness#230]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu 16.10 x64

################################################################################
#                                  EyeWitness                                  #
################################################################################

Starting Web Requests (40 Hosts)
Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Message: 'geckodriver' executable needs to be in PATH. 

Starting VNC/RDP Requests (80 Hosts)
..........

## Any additional information

ran the install script first.

**Comment by ChrisTruncer** [comment]
Merged it in.  Please do a git pull and re-run the setup script.
