### ISSUE TITLE
Issues with HTTPS

### ISSUE THREAD

**Issue by DaScripter** [ChrisTruncer/EyeWitness#232]
## OS Used 
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

## Issue
For whatever reason eyewitness is not taking screen shots of pages with HTTP.  Below are the error messages when scanning.

##Error Messages

Starting Web Requests (151 Hosts)
Attempting to screenshot http://xxx.140.0.128.11
[*] WebDriverError when connecting to http://xxx.140.128.11
Attempting to screenshot https://xxx.140.128.11
[*] WebDriverError when connecting to https://xxx.140.128.11
Attempting to screenshot http://xxx.140.128.12
Attempting to screenshot https://xxx.140.128.12
[*] WebDriverError when connecting to https://xxx.140.128.12
Attempting to screenshot https://xxx.140.128.17

**Comment by ChrisTruncer** [comment]
It looks like you can't connect to anything.  I'm not sure what help I can give with that limited into.  It's working and taking screenshots for me right now.

**Comment by DaScripter** [comment]
Chris, wheres the error log? Ill see if I can find a solution.

**Comment by DaScripter** [comment]
Problem solved - I ran apt-get autoremove and autoclean.   Seems like it was some old drivers or something.  By the way, your tool is amazing.  Thanks!

**Comment by ChrisTruncer** [comment]
Glad to hear it's working!
