### ISSUE TITLE
Relative link in report to RDP screens

### ISSUE THREAD

**Issue by sopsmattw** [ChrisTruncer/EyeWitness#233]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali-rolling

## Pastebin link to error you are encountering
No error, but broken image reference when I move the report folder to different systems.

Priority: minor annoyance :)

## Expected behavior (vs. what you encountered)
Often I will dump information from different scans on a remote box, then pull it local for offline analysis/review/etc. The path to the RDP screenshots in rdp_report.html  are all absolute to the full path on the system where the scan was generated. A simple 
`sed -ie 's|/root/tools/EyeWitness/rdp/screens|./screens|g' rdp_report.html`
will fix the issue. The report can now be opened anywhere as long as the report folder structure and content is maintained.

**Comment by ChrisTruncer** [comment]
thanks for the heads up, I need to check this out

**Comment by ChrisTruncer** [comment]
Just got this fixed and merged into master.  Thanks for letting me know!
