### ISSUE TITLE
Feature suggestion: use POST and GET 

### ISSUE THREAD

**Issue by royharoush** [ChrisTruncer/EyeWitness#235]
Hi, 
I think it would be great to have eyewitness request the page one time using POST and then using GET, and present another result if there is  difference. 

Some web services may present different response based on the method used, so this can help identify these minor difference to understand what's listening on the port. 
thanks,
Roy

**Comment by ChrisTruncer** [comment]
Thanks for the suggestion.  I do think that it is a good idea, but at the moment I am not able to spend the time working on this.  If someone were to submit a pull request, I'd be happy to review it.  Thanks!
