### ISSUE TITLE
setup on Debian 8 requires install of python-bs4

### ISSUE THREAD

**Issue by d4t4king** [ChrisTruncer/EyeWitness#236]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
Debian "(Jessie)" 8.6

## Pastebin link to error you are encountering
NA

## Expected behavior (vs. what you encountered)
setup.sh install all necessary packages.  

## Any additional information
`apt-get install python-bs4 -y` still required after `setup.sh` is run.

**Comment by ChrisTruncer** [comment]
I tested this on Debian stable with an out of the box install, and it worked immediately.  Were you trying to do anything specific that might have caused it to fail?

**Comment by d4t4king** [comment]
Not that I recall.  I will set up a pristine VM and give it another go.

**Comment by DannyCork** [comment]
I did a minimal install of Kali , git cloned Eyewitness , ran setup , then ran

python EyeWitness.py -f urls.txt --web

and got a similar issue

```
root@kali:~/EyeWitness# python EyeWitness.py -f urls.txt --web
Traceback (most recent call last):
  File "EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/root/EyeWitness/modules/db_manager.py", line 4, in <module>
    from objects import HTTPTableObject
  File "/root/EyeWitness/modules/objects.py", line 5, in <module>
    from helpers import strip_nonalphanum
  File "/root/EyeWitness/modules/helpers.py", line 16, in <module>
    from login_module import checkCreds
  File "/root/EyeWitness/modules/login_module.py", line 8, in <module>
    from bs4 import BeautifulSoup as beatsop
ImportError: No module named bs4

```
