### ISSUE TITLE
does EyeWitness support SSL?

### ISSUE THREAD

**Issue by legit** [ChrisTruncer/EyeWitness#237]
Hi,
I'm always getting "[*] ERROR: Web page possibly blank or SSL error!" error while visiting https:// websites.
Does this mean EyeWitness simply doesn't support SSL, or is this something i'm doing wrong?

**Comment by ChrisTruncer** [comment]
Yes, EyeWitness supports SSL.  If you get that error, you either didn't provide it a valid URL, or the XML file you are parsing does not have any open HTTP(S) servers.

**Comment by legit** [comment]
Hey, can you please take a look at this? Thanks!
https://streamable.com/3z3cm

**Comment by ChrisTruncer** [comment]
Just checked it out, it's likely because you're running EyeWitness on Windows.  EyeWitness is designed to run on Linux, and isn't cross compatible with Windows in its current state.

**Comment by legit** [comment]
Ah, I understand now. I'll start using it on a vm then, thanks! :)
