### ISSUE TITLE
Unsupported Marionette protocol version 2, required 3

### ISSUE THREAD

**Issue by jakxx** [ChrisTruncer/EyeWitness#242]
## OS Used - ALL Information (architecture, linux flavor, etc.)
root@yourmomshouse:/tools/EyeWitness# uname -a
Linux segfault 4.3.0-kali1-amd64 1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux

## Pastebin link to error you are encountering
http://pastebin.com/kfUZ8C0p

## Expected behavior (vs. what you encountered)
Capture of web and RDP screenshots

## Any additional information
ran setup script with no issues, nessus file contains both HTTP, HTTPS, and RDP services open

**Comment by ChrisTruncer** [comment]
This should ideally be fixed now.  The setup script was updated to grab the latest version of geckodriver.  Thanks for reporting this!
