### ISSUE TITLE
Argument no-prompt not taken into consideration for directory overwrite question

### ISSUE THREAD

**Issue by nep7un** [ChrisTruncer/EyeWitness#250]
Check below code, since this is still require input from user. I'm calling your script from an other script, so no-prompt is really important for me.
            if os.path.isdir(args.d):
                overwrite_dir = raw_input(('Directory Exists! Do you want to '
                                           'overwrite? [y/n] '))
                overwrite_dir = overwrite_dir.lower().strip()
                if overwrite_dir == 'n':
                    print('Quitting...Restart and provide the proper '
                          'directory to write to!')
                    sys.exit()
                elif overwrite_dir == 'y':
                    shutil.rmtree(args.d)
                    pass
                else:
                    print('Quitting since you didn\'t provide '
                          'a valid response...')
                    sys.exit()

Thanks!

**Comment by ChrisTruncer** [comment]
This should now be fixed, thanks for bringing this to my attention!
