### ISSUE TITLE
[Docker] missing phantomjs binary

### ISSUE THREAD

**Issue by kgersen** [ChrisTruncer/EyeWitness#251]
steps to reproduce:

`docker run -it -v ~/EW:/tmp/EyeWitness/  eyewitness  --single http://www.google.com`

will output
`################################################################################
#                                  EyeWitness                                  #
################################################################################

 [*] Error: You are missing your phantomjs binary!
 [*] Please run the setup script!
`
after examining the container, it appears phantomjs  is located in '/bin' instead of been located in '/EyeWitness/bin' which leads to the error. 

proposed fix: change line 12 of Dockerfile to:

`RUN cd setup && ./setup.sh`

**Comment by ChrisTruncer** [comment]
This should now be fixed

**Comment by ChrisTruncer** [comment]
Thanks for reporting it!
