### ISSUE TITLE
Unrecognized Arguments: --createtargets

### ISSUE THREAD

**Issue by WhiteOakSecurity** [ChrisTruncer/EyeWitness#253]
When running the script with the --createtargets flag, I receive the following error:

EyeWitness.py: error: unrecognized arguments: --createtargets targets.txt

This was attempted with all five (5) types (--all-protocols, web, rdp, vnc, and headless), and with both Nessus and Nmap files.

Command example:
./EyeWitness.py -x nmap.xml --headless --createtargets targets.txt

I looked in EyeWitness.py, but I could not longer see where the createtargets flag is being used to call target_creator anymore.

Thank you for a great tool!

**Comment by ChrisTruncer** [comment]
It's not being called, and it's not an option for the command line, which is why you're getting that error.

It used to be, until the XML parsing was updated
