### ISSUE TITLE
Error making webscreenshots

### ISSUE THREAD

**Issue by Luuk1979** [ChrisTruncer/EyeWitness#255]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux 2.0 x64
Iceweasel webbrowser (most current version)

## Pastebin link to error you are encountering
Error message received for each url in supplied text file
'Message: Missing 'marionetteProtocol' field in handshake'

## Expected behavior (vs. what you encountered)
Trying to make web screenshots using syntax:
./Eyewitness.py -f urllist.txt --web

## Any additional information
Geckodriver log
(process:21247): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
1489064931867	addons.manager	DEBUG	Application has been upgraded
1489064931883	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1489064931889	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1489064931891	addons.xpi	DEBUG	startup
1489064931941	addons.xpi	DEBUG	checkForChanges
1489064931943	addons.xpi	DEBUG	Directory state JSON differs: cache [] state [{"name":"app-global","addons":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"descriptor":"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","mtime":1439382069000,"rdfTime":1435719112000}}},{"name":"app-profile","addons":{"test@autoew.net":{"descriptor":"/tmp/rust_mozprofile.r2IKLs6HykZi/extensions/test@autoew.net","mtime":1489064931000,"rdfTime":1489064931000}}}]
1489064931957	addons.xpi-utils	DEBUG	Opening XPI database /tmp/rust_mozprofile.r2IKLs6HykZi/extensions.json
1489064931957	addons.xpi	DEBUG	New add-on test@autoew.net installed in app-profile
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1489064931988	addons.xpi-utils	DEBUG	Make addon app-profile:test@autoew.net visible
1489064931990	DeferredSave.extensions.json	DEBUG	Save changes
1489064931991	DeferredSave.extensions.json	DEBUG	Save changes
1489064931991	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1489064931994	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1489064931994	DeferredSave.extensions.json	DEBUG	Save changes
1489064931994	DeferredSave.extensions.json	DEBUG	Save changes
1489064931996	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1489064931996	addons.xpi-utils	DEBUG	Updating add-on states
1489064931996	addons.xpi-utils	DEBUG	Writing add-ons list
1489064932418	DeferredSave.extensions.json	DEBUG	Starting timer
iceweasel: Fatal IO error 11 (Resource temporarily unavailable) on X server :1005.
iceweasel: Fatal IO error 11 (Resource temporarily unavailable) on X server :1005.
1489065661562	geckodriver	INFO	Listening on 127.0.0.1:35376
1489065662570	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.uhc8d8y9lnpo
1489065662630	geckodriver	INFO	Listening on 127.0.0.1:55588
1489065663632	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.Jpu4tLXZ5GWh

**Comment by ChrisTruncer** [comment]
I just put EyeWitness on a clean VM of Kali and ran the same command you did, and it completed successfully (generated a screenshot, etc.). Is there any additional information you can provide to help me recreate this?

**Comment by Luuk1979** [comment]
Hi chris,
Tnx for reply. I did the same and it works indeed. I installed it earlier on a previous version of kali. Guessing the iceweasel browser is one version older. Thats how i got to the error.

Luuk

**Comment by Luuk1979** [comment]
The new kali iso now comes with Firefox ESR.
now you get:
Message: Missing 'type' parameter

**Comment by Luuk1979** [comment]
--web gives the message
--headless works by the way.

**Comment by ChrisTruncer** [comment]
Does it still work but it just provides that message? Or does it not work at all with --web?

**Comment by Luuk1979** [comment]
No mate. It creates the folder but no screenies inside it.

**Comment by ChrisTruncer** [comment]
Hm... I just built out a Kali VM, cloned EyeWitness on it, and it's taking screenshots of the websites it's navigating to.

**Comment by ChrisTruncer** [comment]
Closing due to no response, or more data to test with

**Comment by ChrisTruncer** [comment]
@Luuk1979 - Just wanted to let you know that I did look more into this. It looks to be a selenium issue at the moment. I'd say stick with --headless for the time being.

https://github.com/SeleniumHQ/selenium/issues/3654

**Comment by Luuk1979** [comment]
Chris,

I Will. Thx for support and sharing a great tool

Luuk

Verstuurd vanaf mijn iPhone

Op 24 mrt. 2017 om 21:15 heeft ChrisTruncer <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@Luuk1979<https://github.com/Luuk1979> - Just wanted to let you know that I did look more into this. It looks to be a selenium issue at the moment. I'd say stick with --headless for the time being.

SeleniumHQ/selenium#3654<https://github.com/SeleniumHQ/selenium/issues/3654>
