### ISSUE TITLE
Failure to test for NoneType on UA source code compare

### ISSUE THREAD

**Issue by mubix** [ChrisTruncer/EyeWitness#257]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Debian

## Error
```
Traceback (most recent call last):
  File "./EyeWitness.py", line 612, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 541, in multi_mode
    results = dbm.get_complete_http()
  File "/root/eyewitness/modules/db_manager.py", line 150, in get_complete_http
    o.add_ua_data(uao)
  File "/root/eyewitness/modules/objects.py", line 289, in add_ua_data
    difference = abs(len(self.source_code) - len(uaobject.source_code))
TypeError: object of type 'NoneType' has no len()

```

**Comment by ChrisTruncer** [comment]
Hey Rob, thanks for reporting this. Was this a one off thing that happened, or does it consistently happen against a site? Happen to have a public site that I could test this against it? I just want to handle it properly and testing against a site would be easiest to properly handle vs. creating a generic exception handler (I do appreciate you pointing out exactly where it is).

**Comment by mubix** [comment]
Sorry, it's not something I can disclose.

**Comment by ChrisTruncer** [comment]
I just merged a fix which does a check to make sure the values for the source code attribute aren't None. Ideally, that should prevent this issue from occurring.

Thanks for letting me know about this.
