### ISSUE TITLE
crash when --no-prompt and existing directory is specified

### ISSUE THREAD

**Issue by ngvirus** [ChrisTruncer/EyeWitness#262]
## OS Used - ALL Information (architecture, linux flavor, etc.)
CentOS 7
Linux server.be 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## Pastebin link to error you are encountering
Traceback (most recent call last):
  File "./EyeWitness.py", line 593, in <module>
    create_folders_css(cli_parsed)
  File "/root/EW/modules/helpers.py", line 654, in create_folders_css
    os.makedirs(cli_parsed.d)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/var/www/html/reports'

## Expected behavior (vs. what you encountered)
I got this using: ./EyeWitness.py --headless --single https://www.yahoo.com -d /var/www/html/reports --no-prompt
## Any additional information
may be if the directory exists and --no-prompt is used it should override?

**Comment by ChrisTruncer** [comment]
got this merged in, good call!
