### ISSUE TITLE
No screenshot taken when there are TLS/SSL issues

### ISSUE THREAD

**Issue by DavidDeLille** [ChrisTruncer/EyeWitness#268]
## OS Used - ALL Information (architecture, linux flavor, etc.)
latest Kali; details shouldn't matter

## Pastebin link to error you are encountering
I used google.com (172.217.25.142) as an example.
```
Attempting to screenshot https://172.217.25.142
[*] WebDriverError when connecting to https://172.217.25.142
```
Screenshot is taken correctly when using "google.com"

## Expected behavior (vs. what you encountered)
I expected it to mention that a TLS/SSL error was encountered, but still take the screenshot.

## Any additional information
Maybe an command line option could be added to ignore TLS/SSL issues.

Run the following command to recreate:
```
./EyeWitness.py --web --single https://172.217.25.142
```

**Comment by ChrisTruncer** [comment]
If you use --headless instead of --web, does it work?

**Comment by DavidDeLille** [comment]
Headless works. Still, Selenium shouldn't stumble over simple TLS issues.

**Comment by ChrisTruncer** [comment]
I don't believe it is a TLS issue. I believe it is an issue with the version of Firefox that is packaged with Kali linux. I haven't been able to recreate this issue on Debian, but i can on Kali.
