### ISSUE TITLE
EyeWitness.py: cannot connect to X server

### ISSUE THREAD

**Issue by RickTorresJr** [ChrisTruncer/EyeWitness#270]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Using the Dockerfile provided in this Github repository
Docker version 17.03.1-ce, build c6d412e

Command issued:
docker run -it -v $HOME/scans:/tmp/EyeWitness/ eyewitness -x /tmp/EyeWitness/nmap-tcp-scan.xml --vnc

## Expected behavior (vs. what you encountered)
No VNC screenshots are taken. Error returned is:

Starting VNC/RDP Requests (17 Hosts)
EyeWitness.py: cannot connect to X server

**Comment by ChrisTruncer** [comment]
Sounds like xvfb might not be installed. With that said, I don't support a docker install of EyeWitness.

@netanelravid Can you look into this?

**Comment by RickTorresJr** [comment]
I double checked if xvfb is installed and indeed it is (if anyone else is having the issue). I understand not supporting the docker install. Thanks anyway. This is still a great tool.

<img width="442" alt="screen shot 2017-06-20 at 11 01 24 am" src="https://user-images.githubusercontent.com/12430441/27340912-b73e4208-55a9-11e7-9de0-479065e53b2d.png">

**Comment by netanelravid** [comment]
I hope to catch it on the coming Friday
@ChrisTruncer

**Comment by netanelravid** [comment]
Done.
Check out PR #272

**Comment by ChrisTruncer** [comment]
Merged
