### ISSUE TITLE
What port does it go for?

### ISSUE THREAD

**Issue by turnerdb** [ChrisTruncer/EyeWitness#271]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux

## Pastebin link to error you are encountering
No error

## Expected behavior (vs. what you encountered)
We run a nmap scan first and the nmap file shows the ports we want to look at are open.  It seems that EyeWitness is only hitting the first port and not moving through to the other open ports identified during the nmap scan.  Is this an issue that has been encountered and would it be an issue with the commands we run.

## Any additional information
Command:
rm -v ./testNmapfile.xml
nmap  -sS -iL scanfile.txt -p 80,443,3128,3333,3389,5800,5900,8080,8443 -T5 -oX ./testNmapfile.xml
./EyeWitness.py --all-protocols --active-scan  -x ./testNmapfile.xml
#./EyeWitness.py --web --active-scan  -x ./testNmapfile.xml
#./EyeWitness.py --headless --active-scan  -x ./testNmapfile.xml

**Comment by ChrisTruncer** [comment]
It finds any port with a web server running on it based on the service detection nmap does
