### ISSUE TITLE
ImportError: No module named modules

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#273]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali 64 bit

# python --version
Python 2.7.13

## Pastebin link to error you are encountering
Updated an install that worked 50'ish days ago. Tried to run it and got this:

```
Traceback (most recent call last):
  File "./EyeWitness.py", line 13, in <module>
    from modules import db_manager
ImportError: No module named modules
```

Tried swapping around the order of the imports to see if it was a specific one but always got the problem on line 13:

```
Traceback (most recent call last):
  File "./EyeWitness.py", line 13, in <module>
    from modules.helpers import create_folders_css
ImportError: No module named modules.helpers
```

I've not fully ran the setup script but re-ran the apt-get to ensure all the system packages are up-to-date and re-ran the pip installs to sort out all of them.

Checked history and  I didn't do anything special when running it last time, just a simple ./EyeWitness.py, didn't need to specify a different version of Python or anything like that.

## Expected behavior (vs. what you encountered)
Should just work!

## Any additional information
Something to think about while sat on a plane for 8+ hours!

**Comment by ChrisTruncer** [comment]
Hm... I can't seem to trigger this, lets talk

**Comment by bugdiscloseguy** [comment]
Getting the same error!!

**Comment by ChrisTruncer** [comment]
@bugdiscloseguy - can you help give ways to reproduce this?

**Comment by ChrisTruncer** [comment]
Going to close for now, might have been inadvertently fixed at some point, I can't seem to recreate this at the moment. But if someone can, and can write steps to recreate it, I will happily look at this again.
