### ISSUE TITLE
IOError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by AlejandroBaca** [ChrisTruncer/EyeWitness#276]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Linux kali 4.9.0-kali3-686-pae #1 SMP Debian 4.9.18-1kali1 (2017-04-04) i686 GNU/Linux

## Pastebin link to error you are encountering

I have an encountered an issue where EyeWitness crashes when it is provided a very long URL. I have a a list of URLs and some of them exceed 1,200 characters. For example: 

http://www.example.com/m/ad?v=6&id=946f80d41b104b26882908123fd9879f&nv=4.9.0&dn=ABC%2Cafes%204%2Coccam&bundle=free.free.free.free.free&q=z_sdkversion%3A4.9.1%2Cz_impression_id%3Ac7fc633d-ef46-43c3-b7b4-f023756fdbd4%2Cz_slot_name%3AMOB_AMOB_AMOB%2Cz_nexage%3Atrue%2Cz_min_version%3A4.2.1&z=%2B0530&o=p&w=768&h=1280&sc_a=2.0&ct=2&av=5.100&udid=ifa%3Ab34bf686-e4f1-40c2-9d55-8ffec23854bb&dnt=0&mr=1&android_perms_ext_storage=1&request_id=275bfa5391ed41bf892c28f0ef6077bc&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&fail=1&exclude=0a6bc7a355cd4e0bb0f911176ced5588&exclude=0d333a33ebcc41918c2f62b2bfca6702&exclude=2375de2f3b2141c990e2fa092562258f&exclude=2829ea39d6694cc6a5f692e2177e6917&exclude=5889b1a24630447e8a3ff60795d30942&exclude=750ec5c057334dd8b3290986e72b422f&exclude=7b488c2cbed84453989772c810846d09&exclude=8266948230ec480c96108ebb3006906e&exclude=862cf58deb9f4fffa3506f689b217196&exclude=9582213f56f84c20a301e2499a7dbad2&exclude=b43cf5ed7b65475fb3e35c10e4033d1d&exclude=beae0d98d7c94d9dab3cb4cd42938aa5&exclude=c6c4b536a77b412eaa1361974fd783e3&exclude=d85af7fbe6a04309810b417d7eaef2f8&exclude=ef6259891861468e82a1bc07f41e8150&exclude=fe6c536185964649a3d39901b1848572&fail=1

When executing the following command:

`/usr/share/eyewitness/EyeWitness.py -f urlList --web -d urlListResults`

I am presented with the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/eyewitness/EyeWitness.py", line 330, in worker_thread
    cli_parsed, http_object, driver)
  File "/usr/share/eyewitness/modules/selenium_module.py", line 244, in capture_host
    with open(http_object.source_path, 'w') as f:
IOError: [Errno 36] File name too long: '/root/urlListResults/source/http.www.example.com.m.ad.v.6&id.946f80d41b104b26882908123fd9879f&nv.4.9.0&dn.ABC.2Cafes.204.2Coccam&bundle.free.free.free.free.free&q.z_sdkversion.3A4.9.1.2Cz_impression_id.3Ac7fc633d-ef46-43c3-b7b4-f023756fdbd4.2Cz_slot_name.3AMOB_AMOB_AMOB.2Cz_nexage.3Atrue.2Cz_min_version.3A4.2.1&z..2B0530&o.p&w.768&h.1280&sc_a.2.0&ct.2&av.5.100&udid.ifa.3Ab34bf686-e4f1-40c2-9d55-8ffec23854bb&dnt.0&mr.1&android_perms_ext_storage.1&request_id.275bfa5391ed41bf892c28f0ef6077bc&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&exclude.0a6bc7a355cd4e0bb0f911176ced5588&exclude.0d333a33ebcc41918c2f62b2bfca6702&exclude.2375de2f3b2141c990e2fa092562258f&exclude.2829ea39d6694cc6a5f692e2177e6917&exclude.5889b1a24630447e8a3ff60795d30942&exclude.750ec5c057334dd8b3290986e72b422f&exclude.7b488c2cbed84453989772c810846d09&exclude.8266948230ec480c96108ebb3006906e&exclude.862cf58deb9f4fffa3506f689b217196&exclude.9582213f56f84c20a301e2499a7dbad2&exclude.b43cf5ed7b65475fb3e35c10e4033d1d&exclude.beae0d98d7c94d9dab3cb4cd42938aa5&exclude.c6c4b536a77b412eaa1361974fd783e3&exclude.d85af7fbe6a04309810b417d7eaef2f8&exclude.ef6259891861468e82a1bc07f41e8150&exclude.fe6c536185964649a3d39901b1848572&fail.1.txt'
```
I'm assuming this is happening due to the file name length restriction for the ext4 file system. I attempted to create the file using the "cat" command and received a similar error:

```
cat > 'http.www.example.com.m.ad.v.6&id.946f80d41b104b26882908123fd9879f&nv.4.9.0&dn.ABC.2Cafes.204.2Coccam&bundle.free.free.free.free.free&q.z_sdkversion.3A4.9.1.2Cz_impression_id.3Ac7fc633d-ef46-43c3-b7b4-f023756fdbd4.2Cz_slot_name.3AMOB_AMOB_AMOB.2Cz_nexage.3Atrue.2Cz_min_version.3A4.2.1&z..2B0530&o.p&w.768&h.1280&sc_a.2.0&ct.2&av.5.100&udid.ifa.3Ab34bf686-e4f1-40c2-9d55-8ffec23854bb&dnt.0&mr.1&android_perms_ext_storage.1&request_id.275bfa5391ed41bf892c28f0ef6077bc&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&exclude.0a6bc7a355cd4e0bb0f911176ced5588&exclude.0d333a33ebcc41918c2f62b2bfca6702&exclude.2375de2f3b2141c990e2fa092562258f&exclude.2829ea39d6694cc6a5f692e2177e6917&exclude.5889b1a24630447e8a3ff60795d30942&exclude.750ec5c057334dd8b3290986e72b422f&exclude.7b488c2cbed84453989772c810846d09&exclude.8266948230ec480c96108ebb3006906e&exclude.862cf58deb9f4fffa3506f689b217196&exclude.9582213f56f84c20a301e2499a7dbad2&exclude.b43cf5ed7b65475fb3e35c10e4033d1d&exclude.beae0d98d7c94d9dab3cb4cd42938aa5&exclude.c6c4b536a77b412eaa1361974fd783e3&exclude.d85af7fbe6a04309810b417d7eaef2f8&exclude.ef6259891861468e82a1bc07f41e8150&exclude.fe6c536185964649a3d39901b1848572&fail.1.txt' 
bash: http.www.example.com.m.ad.v.6&id.946f80d41b104b26882908123fd9879f&nv.4.9.0&dn.ABC.2Cafes.204.2Coccam&bundle.free.free.free.free.free&q.z_sdkversion.3A4.9.1.2Cz_impression_id.3Ac7fc633d-ef46-43c3-b7b4-f023756fdbd4.2Cz_slot_name.3AMOB_AMOB_AMOB.2Cz_nexage.3Atrue.2Cz_min_version.3A4.2.1&z..2B0530&o.p&w.768&h.1280&sc_a.2.0&ct.2&av.5.100&udid.ifa.3Ab34bf686-e4f1-40c2-9d55-8ffec23854bb&dnt.0&mr.1&android_perms_ext_storage.1&request_id.275bfa5391ed41bf892c28f0ef6077bc&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&fail.1&exclude.0a6bc7a355cd4e0bb0f911176ced5588&exclude.0d333a33ebcc41918c2f62b2bfca6702&exclude.2375de2f3b2141c990e2fa092562258f&exclude.2829ea39d6694cc6a5f692e2177e6917&exclude.5889b1a24630447e8a3ff60795d30942&exclude.750ec5c057334dd8b3290986e72b422f&exclude.7b488c2cbed84453989772c810846d09&exclude.8266948230ec480c96108ebb3006906e&exclude.862cf58deb9f4fffa3506f689b217196&exclude.9582213f56f84c20a301e2499a7dbad2&exclude.b43cf5ed7b65475fb3e35c10e4033d1d&exclude.beae0d98d7c94d9dab3cb4cd42938aa5&exclude.c6c4b536a77b412eaa1361974fd783e3&exclude.d85af7fbe6a04309810b417d7eaef2f8&exclude.ef6259891861468e82a1bc07f41e8150&exclude.fe6c536185964649a3d39901b1848572&fail.1.txt: File name too long
```

## Expected behavior (vs. what you encountered)

Should just work!

**Comment by ChrisTruncer** [comment]
For now, this is an unfortunate design decision I made a while back to help ensure that data isn't overwritten. For the time being this will be the way that it stays. Unfortunately, the result of that would be these extremely long google URLs will encounter issues.

Thanks for reporting this.

**Comment by AlejandroBaca** [comment]
Thank you for looking into this issue and providing an answer, Chris! Regardless, I appreciate you creating and maintaining this tool.
