### ISSUE TITLE
Receive semaphore expired

### ISSUE THREAD

**Issue by turnerdb** [ChrisTruncer/EyeWitness#277]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali 2017.1 - Fully upgraded

## Pastebin link to error you are encountering
the semaphore timeout period has expired

## Expected behavior (vs. what you encountered)
Ip should be attemtped by EyeWitness, instead while performing scans on smaller IP lists eyewitness takes the NIC out and makes the box unresponsive.

## Any additional information
I have never had this issue while scanning large numbers of IP, 1000+, but for some reason it happens when we do under 200 at a time.  I have also attached a list of some other issues that we have encountered along with the commands we use.
[EyeWitness Road Blocks.docx](https://github.com/ChrisTruncer/EyeWitness/files/1252127/EyeWitness.Road.Blocks.docx)

**Comment by ChrisTruncer** [comment]
Is there some way that you can post something that would allow me to re-create this? However, EyeWitness doesn't rate limit its requests. You could potentially add a large jitter and/or reduce the number of threads being used by EyeWitness.

**Comment by ChrisTruncer** [comment]
The datafile is used to add in credentials for live testing, however this stuff needs to be manually added in for each web app that you want supported. So this is a manual process (which I am more than happy to have pull requests for).

3. That seems like a valid issue for @chango77747 to look into.

4. There shouldn't be a leak for specifically 200 hosts.

**Comment by turnerdb** [comment]
So an additional issue we are having is that EyeWitness will say certain credentials worked but when I go to verify they do not.  Is there a cause for this?

**Comment by ChrisTruncer** [comment]
The definition for what is considered correct or not should be in the datafile. @chango77747 - can you look at this?

**Comment by turnerdb** [comment]
@chango77747 Any chance there is a update on this issues you have been tagged on?
