### ISSUE TITLE
Enhancement with Search.py - no http header in database

### ISSUE THREAD

**Issue by phackt** [ChrisTruncer/EyeWitness#278]
Hello, i would like to improve the Search.py script in order to look for http_headers too. Unfortunately adding in db_manager.py->search_for_term function:

```
if search in o.source_code or search in o.page_title or search in o.http_headers:
```

Does not return anything, all http_headers being empty ('{}'). Can you help me to figure out why the http_headers are empty and if they are stored. I think it could be interesting to look into headers too. 

Thanks in advance.

**Comment by ChrisTruncer** [comment]
If you can use something like sqlitebrowser you can view the data stored in the included database. The data is currently stored as a binary blog, but it does include header data. However, that data is stored within the blob and isn't separate

**Comment by ChrisTruncer** [comment]
closing since I haven't heard back
