### ISSUE TITLE
add-http-ports / add-https-ports are not working

### ISSUE THREAD

**Issue by phackt** [ChrisTruncer/EyeWitness#279]
Hello,
I just run EyeWitness and launched a wireshark. While i was using the option add-http-ports, i saw that not extra ports was requested. Then i simply executed this command:

```
./EyeWitness.py --single localhost --add-http-ports 8000 --web
```

Launching a ncat on my localhost on port 8000 did not trigger any request. I'm on the master. I read that some issues are dealing with this behavior but finally my question is:

Is there any reason why this can not work this way ? Anyway i can create a file with url on specific ports, it s not a big deal.

Thanks in advance,

**Comment by ChrisTruncer** [comment]
To be honest, I've not tested this when using --single, as I don't believe the tool is supposed to add on ports to a single URL. When using --single, it is assumed you are only testing a single system, not a domain plus some extra ports.

You should be able to provide a file with -f <filename> and then use --add-http-ports and it would add the specified port number to the URLs in the file.

**Comment by ChrisTruncer** [comment]
Closing due to lack of response

**Comment by belane** [comment]
Looks like `--add-http-ports` doesn't work even with -f option.
