### ISSUE TITLE
Wrong links to images in the html report

### ISSUE THREAD

**Issue by BBerastegui** [ChrisTruncer/EyeWitness#280]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Docker's Debian (latest) and latest version pulled from EyeWitness repo

## Error description

The images linked in the second column of the HTML report do no correspond to the url in the first column.

See the example below (https://business.prod.facebook.com pointing to http://business.facebook.com screenshot):

`<br><br><a href="source/https.business.prod.facebook.com.txt"
                target="_blank">Source Code</a></div></td>
                <td><div id="screenshot"><a href="screens/http.business.facebook.com.png"
                target="_blank"><img src="screens/http.business.facebook.com.png"
                height="400"></a></div></td></tr></div>`

## Expected behavior (vs. what you encountered)

Screenshot corresponding to the correct url.

## Any additional information

N/A

**Comment by BBerastegui** [comment]
Please also take into account the command used for this behaviour to happen:

`python EyeWitness.py --headless --prepend-https -d /tmp/outputdir -f /tmp/sites_list.txt --no-prompt`

**Comment by ChrisTruncer** [comment]
Yup, I can re-create this. Thanks for reporting it, I'll look into it

**Comment by ChrisTruncer** [comment]
Ah, so I forgot, this isn't a bug. EyeWitness looks at all the images and deduplicates them. If any images are the same, it will only keep one of them and rewrite all others to use that one image.
