### ISSUE TITLE
Docker Build | no 'moz:firefoxOptions.binary' capability provided

### ISSUE THREAD

**Issue by zeknox** [ChrisTruncer/EyeWitness#281]
## OS Used
MAC OS Sierra 10.12.5
Docker version 17.06.2-ce, build cec0b72

## Output
<pre>
################################################################################
#                                  EyeWitness                                  #
################################################################################

Starting Web Requests (1 Hosts)
Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
</pre>

## Expected behavior (vs. what you encountered)
Expected to receive screenshot of HTTP / HTTPS services but it appears that Docker build process is broken or the binary location is not properly assigned when attempting to run eyewitness from the docker image.

Docker build process was run as documentation stated and appeared to complete without issues.

## Any additional information

Docker command run that invokes the error:
<pre>
docker run --rm -it -v ~/Eyewitness:/tmp/EyeWitness eyewitness -f /tmp/EyeWitness/1_192.168.1.1.txt --all-protocols
</pre>

**Comment by PatrikFehrenbach** [comment]
You are using the Docker version, which is only suitable for non-headless modes (there is no graphical interface installed) you should use the ```--headless``` tag.

**Comment by zeknox** [comment]
Thanks for the update.  I had tried the ''--headless'' tag as well last night but same result.  Let me test once more with the headless to validate and report back. Cheers.

**Comment by ChrisTruncer** [comment]
Was this able to work where I can close this issue?

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard anything.

**Comment by zeknox** [comment]
hey sorry for the delay here, looks like `--headless` was the answer

**Comment by ChrisTruncer** [comment]
Awesome,

Glad to hear it. Thanks for confirming.

**Comment by ayoubfathi** [comment]
You should remove --all-protocols (or --web) in order to use --headless.
