### ISSUE TITLE
Lint pass over python code

### ISSUE THREAD

**Issue by paalbra** [ChrisTruncer/EyeWitness#282]
Using a linter like https://www.pylint.org/ emits a list of issues in the python code.

Some of the issues are hurting readability and maintainability, and should be resolved.

I would suggest doing a full lint pass over the code base.

**Comment by ChrisTruncer** [comment]
I think basically the same comments from #283 apply to this issue as well. With that said, I also do use a linter, but there are times where I've preferred it how it is. Now, is that true for all instances, likely not. But again, this is something that is just a much larger "issue" than I think you realize, and it can be frustrating to receive a github issue like this.

**Comment by paalbra** [comment]
I'm sorry that you feel frustrated by these issues. I meant no harm by creating them. I'm not aware of any other forum where EyeWitness can be discussed and I therefore thought that issues would be the best way to get the discussion going. Please guide me if there are another options available.

I was prepared to contribute to both issues and I'm currently working on a pull-request for this issue.

I would much rather contribute here than create a fork of the repo, but it's hard for me to contribute to a repo where there is no open discussion.
