### ISSUE TITLE
EyeWitness.exe Missing!

### ISSUE THREAD

**Issue by MuhammadKhizerJaved** [ChrisTruncer/EyeWitness#288]
As Mentioned in https://github.com/ChrisTruncer/EyeWitness/blob/master/Windows/DownloadExe.txt

The Download Link https://www.christophertruncer.com/InstallMe/EyeWitness.exe Now Working :/

**Comment by ChrisTruncer** [comment]
Yeah, it's not built. I'll remove the reference. Thanks
