### ISSUE TITLE
Setup - grep: /etc/issue: No such file or directory

### ISSUE THREAD

**Issue by davidmthomsen** [ChrisTruncer/EyeWitness#289]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Mac OS X

## Pastebin link to error you are encountering
EyeWitness/setup$ sudo ./setup.sh
cat: /etc/issue: No such file or directory
#######################################################################
#                          EyeWitness Setup                           #
#######################################################################

grep: /etc/issue: No such file or directory
[Error]:  is not supported by this setup script.

## Expected behavior (vs. what you encountered)
Setup script runs

**Comment by ChrisTruncer** [comment]
EyeWitness won't run on Mac, it requires a variety of different packages. I'd recommend running it in Debian within a Virtual Machine.

**Comment by davidmthomsen** [comment]
Gotcha!
No problem. Thanks for the prompt response!
