### ISSUE TITLE
Issue with '--single' flag. EyeWitness fails to run.

### ISSUE THREAD

**Issue by Seceventspen** [ChrisTruncer/EyeWitness#291]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Ubuntu 16.04 LTS (I know this is a documented OS for Eyewitness to be used on)
Kali 2017 v2

## Pastebin link to error you are encountering

No error on screen, so no link

## Expected behavior (vs. what you encountered)

Ubuntu 16.04LTS -- install went fine, no errors or missing dependencies
When using './EyeWitness.py --single https://target-domain.com' - This results in just the help message being replayed to the screen.

Kali 2017 v2 -- again, install went fine, no errors or missing dependencies
Same issue as above when using the '--single' flag to target a single URL

## Any additional information

No on-screen error messages so unable to trouble shoot or provide output.

**Comment by ChrisTruncer** [comment]
You just closed this without any info, can you please provide any information that you found?

**Comment by digininja** [comment]
I pointed out to him that he needed the --headless type flag to tell it
what to scan.

**Comment by Seceventspen** [comment]
Apologies all! I didn't realise I hadn't hit the comment button to save the reason why I was closing the issue! As @digininja pointed out after a conversation we had, it seems I may have been omitting a flag to enable it to run. The --headless flag wasn't listed in the options needs to run against a single host in the wiki.

**Comment by ChrisTruncer** [comment]
Ah nice, thanks for the help and update!
