### ISSUE TITLE
Createtargets does not create file

### ISSUE THREAD

**Issue by rdjotut** [ChrisTruncer/EyeWitness#294]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali 2017.2 Rolling

## Expected behavior (vs. what you encountered)
createtargets function does not create file, no error just does not create it

## Any additional information
Also i noticed that the source xml file needs to be a direct path or it fails

**Comment by ChrisTruncer** [comment]
I need more information please. However, if you do run EyeWitness with the -x and --web, you should have a file called parsed_urls.txt, or something similar to that with your parsed data.

**Comment by ChrisTruncer** [comment]
Closed since I have not received a response.
