### ISSUE TITLE
Kali 2016.3 Cause the virtual machine stuck

### ISSUE THREAD

**Issue by Tren** [ChrisTruncer/EyeWitness#297]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali 2016.3
## Pastebin link to error you are encountering
Scan more than one hundred and eighty domain names, the virtual machine stuck

**Comment by ChrisTruncer** [comment]
There isn't enough info to reproduce anything.  Please provide information to allow me to look into this.
