### ISSUE TITLE
Latest Code Does Not Respect Results Flag + other bug

### ISSUE THREAD

**Issue by bmoar** [ChrisTruncer/EyeWitness#309]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu 16.04 x86_64, fresh install

`EyeWitness.py -f /http_urls.txt --results 1000 --headless --threads 5`

## Pastebin link to error you are encountering

https://imgur.com/JC5tact

As you can see in the above screenshot, there are not 1000 results per page. It is limited to 100 per page.

## Expected behavior (vs. what you encountered)

Older versions of eyewitness would put each group of results on separate page. For example, if I specified the command as:

`EyeWitness.py -f /http_urls.txt --results 1000 --headless --threads 5`

It generated a report of NUM_HOSTS / NUM_RESULTS. 10000 hosts screenshotted / 1000 results would produce a report of 10 pages, each page being report{0..10}.html

It appears that something has changed in the reporting format. The latest version of eyewitness seems to generate a report.html file containing every result on a single .html page that completely disregards the --results flag.

This is very undesirable behavior for processing large amounts of screenshots. I have a report with 50k hosts, and it's basically impossible to navigate through the report now because instead of just scrolling with pageup/pagedown through 1000 results on each .html page, eyeballing for interesting results, I have to find the pagination buttons on a massive .html file and click them individually. In addition, I notice strange behavior when clicking said pagination buttons. The page jumps, and then I cannot locate where I am in the results. This is compounded by the fact that there's now 5 sections all on the same .html page, for errors, 403/401, etc. that all blend together.

Is there an option or an easy way to get the old report generating logic back? I can write some python if need be, but this new report format just isn't cutting it for 50k hosts.

I am sorry I kind of just ripped apart the new format. I really do appreciate the amazing work this tool does and the effort you put into it. Thank you.

**Comment by jpinkham** [comment]
@bmoar: Have you tried checking out an older version of the branch? This could help narrow the window of when the bug/change in question was introduced.  It’s pretty straightforward, if you’re comfortable with git: https://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit

**Comment by ChrisTruncer** [comment]
I am looking into reverting back to the old version of the codebase which uses the older report. I will keep the new report in case people use it, however it will be in a separate branch.

**Comment by ChrisTruncer** [comment]
Closing this for now since I merged back in the original report. Please open a new issue if anything is outstanding.
