### ISSUE TITLE
Getting error while trying to load urls from files

### ISSUE THREAD

**Issue by infosecsecurity** [ChrisTruncer/EyeWitness#313]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali

## Any additional information

Getting this error while trying to load targets from .txt file or nmap .xml output

ERROR: You didn't give me a valid file name! I need a valid file containing URLs!

The urls file has one url per line

site.com
dev.site.com
prod.site.com

**Comment by ChrisTruncer** [comment]
Hi,

You didn’t provide enough information for me to help with this. Please provide a pastebin link to your console output or give more information for me to recreate this.

Thanks

**Comment by ChrisTruncer** [comment]
Closing since I don't have a response. Please respond with additional details if this should be reopened.

**Comment by infosecsecurity** [comment]
Sorry for the delay.
So I'm running this command: eyewitness --prepend-https -f list --all-protocols --headless
and i'm getting is this error: ERROR: You didn't give me a valid file name! I need a valid file containing URLs!
![screenshot from 2018-03-29 18-19-02](https://user-images.githubusercontent.com/7826342/38114187-d1f31f62-337d-11e8-9c2c-e7b3cdc2e006.png)

**Comment by johnsmith344** [comment]
Dear Chris,

I am facing the same error.

I have an input file (sitedomains.txt) with subdomains listed like
**_a.site.com
b.site.com
c.site.com_**

and I use the command "**_eyewitness -f sitedomains.txt -d screen2 --web_**".

However I get the same error as mentioned by the user above.

![error](https://user-images.githubusercontent.com/38156186/38454114-db97be38-3a71-11e8-8dd5-3d9acc90193f.png)

Please check.

Thanks
John

**Comment by johan-lindahl** [comment]
The problem could be that you need the full path to the file such as /root/mydir/list, I had this issue on Kali linux.

**Comment by ericnyamu1** [comment]
am suffering from the same problem.am using docker image.it keeps saying `ERROR: You didn't give me a valid file name! I need a valid file containing URLs!` and trust me i know how a url looks like

**Comment by carhackpils** [comment]
You need to give the absolute path of your file for it to work

**Comment by cpt-kernel** [comment]
I have the same issue with docker, I am giving the full path to the file. 

Example command: 

`sudo docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp.X11-unix -v ~/Data/RCS/results:/tmp/EyeWitness eyewitness --all-protocols -f /tmp/EyeWitness/ips.txt --no-dns --timeout 6 --threads 12`

**ERROR: You didn't give me a valid file name! I need a valid file containing URLs!**

But I can `cat /tmp/EyeWitness/ips.txt`

**Comment by Karanverma0671** [comment]
i run this command but i show the error 
ERROR: You potentially provided an mal-formed URL!

**Comment by muhammadfarras** [comment]
I have faced this problem. Based on docker, if you want add all files and folder, you have to using absolute path and a dot.
```
docker run \
    --rm \
    -it \
    -v $(pwd)/.:/tmp/EyeWitness \
    eyewitness \
    -f /tmp/EyeWitness/urls
```

After I adding dot sign, EyeWitness is runs

**Comment by ram8537** [comment]
Had the issue with Docker and got it working by binding the txt file with the URLs to the Docker container.

This the Docker Compose I used to get it running (replace 'ENTER-DIRECTORY-YOU-WANT-OUTPUT-FILES-IN', 'ENTER-FULL-PATH-OF-YOUR-URLS-TXT-FILE' accordingly):

**eyewitness-docker-compose.yaml**
```
services:
  eyewitness-container:
    image: eyewitness
    volumes:
      - ENTER-DIRECTORY-YOU-WANT-OUTPUT-FILES-IN:/tmp/EyeWitness
      - type: bind
        source: ENTER-FULL-PATH-OF-YOUR-URLS-TXT-FILE
        target: /tmp/EyeWitness/urls.txt
    command: --web -f /tmp/EyeWitness/urls.txt
```

Then run it with: ```docker compose -f eyewitness-docker-compose.yaml up```
