### ISSUE TITLE
Traceback error when I try to use argument "-f urls.txt --web"

### ISSUE THREAD

**Issue by BlackPearl01** [ChrisTruncer/EyeWitness#314]
Hello,

## OS Used - ALL Information (architecture, linux flavor, etc.)

First, thank for your tool!

I'm on Kali Linux (kali-rolling) and I try to use EyeWitness. I downloaded your tool (git clone...) and I've successfully running "setup.sh".

So after that, I tried this command: ``/EyeWitness.py -f myurls.txt --web``. On the file I've just some URLs (one per line) like this ``https://www.example.com/aaa``

## Pastebin link to error you are encountering

`````````````
################################################################################
#                                  EyeWitness                                  #
################################################################################

Traceback (most recent call last):
  File "./EyeWitness.py", line 634, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 443, in multi_mode
    url_list, rdp_list, vnc_list = target_creator(cli_parsed)
  File "/root/Bureau/EyeWitness/modules/helpers.py", line 512, in target_creator
    command_line_object.f, command_line_object)
  File "/root/Bureau/EyeWitness/modules/helpers.py", line 427, in textfile_parser
    port_number = int(url_again.split(":")[2].split("/")[0])
`````````````

Do you know why I've this error? I do something wrong?

Thank for your help !

**Comment by ChrisTruncer** [comment]
Can you provide more information? I’ve run essentially the same command without getting an error.

Thanks.

**Comment by ChrisTruncer** [comment]
Closing this since I don't have a response.
