### ISSUE TITLE
Python program enhancement

### ISSUE THREAD

**Issue by arcsector** [ChrisTruncer/EyeWitness#315]
Hello there,

Is there a way to use this as a python module? If not it seems a bit useless to those of us with bigger networks and larger counts of both static and dynamic IP's.

I'm proposing a python module which gives the user base full functionality. Close this if it's not in your scope.

**Comment by ChrisTruncer** [comment]
“This seems a bit useless” might not be the best way to ask for help.

There isn’t a module for this, as it was designed to be a stand-alone tool. I’ve personally used this in very large environments, and it is able to operate in them.

**Comment by ChrisTruncer** [comment]
With no response, I'll go ahead and close this out.

**Comment by arcsector** [comment]
Hey there Chris,

Sorry about the negativity. I let my day get the better of my mood; I apologize. You're right in that it was an inappropriate way to propose an enhancement.

**Comment by ChrisTruncer** [comment]
No worries,

Happens to me/everyone too, so not a big deal.

If you are running into specific problems, please let me know. I’ve tested this, and I know of others, who have tested EyeWitness into the tens of thousands of systems. I believe it should work larger than that too.
