### ISSUE TITLE
JSON log with full info about the host

### ISSUE THREAD

**Issue by BBerastegui** [ChrisTruncer/EyeWitness#316]
It'll be really useful to have the option of generating a log (if it's json, even better) with all the information about the screenshots that were successful in the following format:

`{
	"host": "www.google.com",
	"port": "443",
	"protocol": "https",
	"screenshot": "$OUTPUT_DIR/https.google.com.443.jpg"
}`

The main reason for me to ask for this is that I've been trying to add EyeWitness into a workflow and I haven't been able to keep the "track" of the `protocol://host:port, screenshotfile`, as the filenames are not really "script-friendly".

As a summary, what I would like to be able to do is to parse a file and easily get the host, the port, the protocol, and the path where the screenshot of that site was done, so I can move/copy it from there knowing where it came from.

I've been playing around with the `http_object` element, as I think **almost** all this information is stored there:
`http_object.remote_system` and `http_object._screenshot_path`
But I would like to hear from you how would you like to implement this properly.

Cheers !

**Comment by ChrisTruncer** [comment]
Just got this merged in. It was a fast addition to have it output to CSV, so that's currently what is tracking the status of each request. Hope this helps!

**Comment by BBerastegui** [comment]
Funny thing, I was actually doing almost the exact same:

I'll give it a try soon ! Thanks !

`+            o = urlparse(http_object.remote_system)
+            json_log_entry["hostname"] = o.hostname
+            if o.port is None:
+                if o.scheme == "https":
+                    json_log_entry["port"] = 443
+                elif o.scheme == "http":
+                    json_log_entry["port"] = 80
+            else:
+                json_log_entry["port"] = o.port
+            json_log_entry["scheme"] = o.scheme
+            json_log_entry["screenshot_path"] = http_object._screenshot_path
+            print(json.dumps(json_log_entry))`
