### ISSUE TITLE
Throwing unknown error

### ISSUE THREAD

**Issue by bugdiscloseguys** [ChrisTruncer/EyeWitness#321]
Hey,

I was trying to install the script & it threw me an unknown error 

[Error]:  is not supported by this setup script.

Thanks

**Comment by bugdiscloseguys** [comment]
![screen shot 2018-04-06 at 8 12 30 am](https://user-images.githubusercontent.com/25739971/38401287-749db5e8-3972-11e8-9d03-77b7b29f7b04.png)

Screenshot Attached

**Comment by ChrisTruncer** [comment]
Please provide all the information requested when filling out an issue or else I don’t have enough to help.

**Comment by ChrisTruncer** [comment]
Also, you're trying to run the setup script which uses apt on a mac, which won't work. If you need/want to use it on your mac, please browse the setup script and manually install the requirements.

**Comment by ravirajbasis** [comment]
Hi

Facing a similar error:

[Error]: Pop!_OS is not supported by this setup script.

Thanks
rraj
