### ISSUE TITLE
Error while trying to load urls from files

### ISSUE THREAD

**Issue by johnsmith344** [ChrisTruncer/EyeWitness#322]
Dear Chris,

I am facing the same error.

I have an input file (sitedomains.txt) with subdomains listed like
**_a.site.com
b.site.com
c.site.com_**

and I use the command "**_eyewitness -f sitedomains.txt -d screen2 --web_**".

However I get the same error as mentioned by the some user earlier.

![error](https://user-images.githubusercontent.com/38156186/38454133-462b9b02-3a72-11e8-84f5-74118108bc1c.png)

Please check.

Thanks,
John.

**Comment by ChrisTruncer** [comment]
Hi there, you didn't provide all the information I need in order to debug this. This is requested when you create a new issue. Please provide all the requested info

**Comment by ChrisTruncer** [comment]
Closing this due to no response. However, based on information provided, you shouldn't really be encountering a problem. If you still are, please create a new issue and provide all the requested information.
