### ISSUE TITLE
selenium not found.

### ISSUE THREAD

**Issue by pinkstarfish** [ChrisTruncer/EyeWitness#323]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu Linux 16.04.4 LTS with xfce

## Pastebin link to error you are encountering
https://pastebin.com/n71AamSk

## Expected behavior (vs. what you encountered)
Expected behavior == run the tool with no issues after running setup.sh.  All requirements were met, and setup.sh installed selenium with no issues.  

Encountered behavior == selenium not found error after issuing ./EyeWitness -f ~/path/to/list.txt --web and --headless

## Any additional information
N/A  
I appreciate your time!

**Comment by ChrisTruncer** [comment]
Can you go into the code and try to remove that specific check EyeWitness does to see if selenium exists, and see what error it displays? It looks like everything should be installed, so not really sure why you'd be getting this error.

**Comment by pinkstarfish** [comment]
Will do.  I'll post an updated response tomorrow.

**Comment by ChrisTruncer** [comment]
Checking back in on this...

**Comment by jslirola** [comment]
Hi, same issue here. I commented the code in `modules/phantom_module.py` and now this is the new error:
```bash
:0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
[*] RDP libraries not found.
[*] Please run the script in the setup directory!
```

**Comment by ChrisTruncer** [comment]
My guess with the missing dependencies is that the setup script was not run to install everything. Please make sure that you do run it.
