### ISSUE TITLE
error running eyewitness

### ISSUE THREAD

**Issue by Gam-7** [ChrisTruncer/EyeWitness#325]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

## Pastebin link to error you are encountering
https://pastebin.com/tTV60QTw

## Expected behavior (vs. what you encountered)
expected tool to run as normal. Am just getting errors

## Any additional information
I installed via git clone

**Comment by ChrisTruncer** [comment]
What is the command you are running that is causing the error? Also, does it work if you don’t have it test the active password check?

**Comment by Gam-7** [comment]
/EyeWitness.py -f urls.txt 
where urls.txt is a file I put in the directory the file urls.txt is just a list of urls. I am not sure what you mean by active password check sorry?

**Comment by ChrisTruncer** [comment]
Do you have a clean VM you can test with? After installing with apt and git, it can mess with dependencies. I’m able to run this on a clean Debian VM I have right now.

**Comment by Gam-7** [comment]
This is the error message I receive when I run 

eyewitness from terminator installed via APT 

![eyewitness](https://user-images.githubusercontent.com/38298059/39593963-43b33b32-4f03-11e8-8ebd-8d9802975265.png)

**Comment by ChrisTruncer** [comment]
Please don’t install via apt. Please test on a clean VM and install via git.

**Comment by Gam-7** [comment]
That solved the issue thanks. (Installing on a clean vm)

**Comment by ChrisTruncer** [comment]
Awesome, thanks for letting me know!
