### ISSUE TITLE
Traceback issue on resume

### ISSUE THREAD

**Issue by turnerdb** [ChrisTruncer/EyeWitness#328]
## OS Used - ALL Information (architecture, linux flavor, etc.)
CentOS 7

## Pastebin link to error you are encountering
08:33:14:t###     [*] Loading Resume Data...
08:33:14:t###     Loaded Resume Data with the following options:
08:33:14:t###
08:33:14:t###     Input File: None
08:33:14:t###     Engine(s): PhantomJS
08:33:14:t###     Threads: 4
08:33:14:t###     Output Directory: /opt/EyeWitness-master/05142018_161713
08:33:14:t###     Timeout: 7
08:33:14:t###
08:33:16:t###     Traceback (most recent call last):
08:33:16:t###       File "./EyeWitness.py", line 634, in <module>
08:33:16:t###         multi_mode(cli_parsed)
08:33:16:t###       File "./EyeWitness.py", line 562, in multi_mode
08:33:16:t###         sort_data_and_write(cli_parsed, results)
08:33:16:t###       File "/opt/EyeWitness-master/modules/reporting.py", line 225, in sort_data_and_write
08:33:16:t###         html += obj.create_table_html()
08:33:16:t###       File "/opt/EyeWitness-master/modules/objects.py", line 241, in create_table_html
08:33:16:t###         for key, value in self.headers.items():
08:33:16:t###     AttributeError: 'str' object has no attribute 'items'

## Expected behavior (vs. what you encountered)
Finalizing the report

## Any additional information
I believe this is the same or similar issue we ran in before.  I am running the Recategorize script on the db to try and get the report in the meantime.

**Comment by ChrisTruncer** [comment]
Did recategorize work for you? The only reason this would be hitting is it is likely something isolated to the specific site, maybe no headers were sent? Could you let me know if it is a public site so I can try to recreate this?

**Comment by turnerdb** [comment]
The recate script gets stuck while the report is attempting to compile and then throws the error.

**Comment by ChrisTruncer** [comment]
Are you able to share the ew.db file or even better, the site that it is getting stuck on?

**Comment by ChrisTruncer** [comment]
If you can provide this info, I will gladly look into it. Otherwise I will have to close this just because I don't have the ability to recreate it.

**Comment by turnerdb** [comment]
Yes sorry. This can be closed.  It only happens on one subnet for some reason.   I believe it’s firewall related. 

Sorry for the delay in response. I have been out.  

Devin.
