### ISSUE TITLE
error running Eyewitness on kali linux

### ISSUE THREAD

**Issue by Gam-7** [ChrisTruncer/EyeWitness#330]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

## Pastebin link to error you are encountering
https://pastebin.com/adjvPfdf << unlisted expires in 7 days 

## Expected behavior (vs. what you encountered)
error occurred after updating to latest version today 

## Any additional information

error occurs after entering command ./Eyewitness.py -f urls.txt --web

**Comment by Gam-7** [comment]
I initially thought it was the urls not properly formed eg
example.com instead of https://www.example.com
but then I tested that with a separate urls.txt file using just 
google.com
twitter.com
facebook.com
and some others and it worked fine, so I am wondering if there a file size limit? the particular file (urls.txt) I am using is 319kb

**Comment by ChrisTruncer** [comment]
Can you provide the websites you are scanning?

**Comment by ChrisTruncer** [comment]
No, there’s no size limit for the urls, or the url file.

**Comment by Gam-7** [comment]
I have just dm you on twitter

**Comment by ChrisTruncer** [comment]
This is because you have two urls on the same line, more info in the e-mail to you
